/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooLegendre5Pdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

#include "legendre5f5.h"

ClassImp(RooLegendre5Pdf) 

 RooLegendre5Pdf::RooLegendre5Pdf(const char *name, const char *title, 
                        RooAbsReal& _costheta0,
                        RooAbsReal& _costheta1,
                        RooAbsReal& _costheta2,
                        RooAbsReal& _phi1,
                        RooAbsReal& _phi2,
                        RooAbsReal& _c00000,
                        RooAbsReal& _c00001,
                        RooAbsReal& _c00002,
                        RooAbsReal& _c00004,
                        RooAbsReal& _c00006,
                        RooAbsReal& _c00010,
                        RooAbsReal& _c00011,
                        RooAbsReal& _c00012,
                        RooAbsReal& _c00014,
                        RooAbsReal& _c00016,
                        RooAbsReal& _c00020,
                        RooAbsReal& _c00021,
                        RooAbsReal& _c00022,
                        RooAbsReal& _c00024,
                        RooAbsReal& _c00026,
                        RooAbsReal& _c00100,
                        RooAbsReal& _c00101,
                        RooAbsReal& _c00102,
                        RooAbsReal& _c00104,
                        RooAbsReal& _c00106,
                        RooAbsReal& _c00110,
                        RooAbsReal& _c00111,
                        RooAbsReal& _c00112,
                        RooAbsReal& _c00114,
                        RooAbsReal& _c00116,
                        RooAbsReal& _c00120,
                        RooAbsReal& _c00121,
                        RooAbsReal& _c00122,
                        RooAbsReal& _c00124,
                        RooAbsReal& _c00126,
                        RooAbsReal& _c00200,
                        RooAbsReal& _c00201,
                        RooAbsReal& _c00202,
                        RooAbsReal& _c00204,
                        RooAbsReal& _c00206,
                        RooAbsReal& _c00210,
                        RooAbsReal& _c00211,
                        RooAbsReal& _c00212,
                        RooAbsReal& _c00214,
                        RooAbsReal& _c00216,
                        RooAbsReal& _c00220,
                        RooAbsReal& _c00221,
                        RooAbsReal& _c00222,
                        RooAbsReal& _c00224,
                        RooAbsReal& _c00226,
                        RooAbsReal& _c01000,
                        RooAbsReal& _c01001,
                        RooAbsReal& _c01002,
                        RooAbsReal& _c01004,
                        RooAbsReal& _c01006,
                        RooAbsReal& _c01010,
                        RooAbsReal& _c01011,
                        RooAbsReal& _c01012,
                        RooAbsReal& _c01014,
                        RooAbsReal& _c01016,
                        RooAbsReal& _c01020,
                        RooAbsReal& _c01021,
                        RooAbsReal& _c01022,
                        RooAbsReal& _c01024,
                        RooAbsReal& _c01026,
                        RooAbsReal& _c01100,
                        RooAbsReal& _c01101,
                        RooAbsReal& _c01102,
                        RooAbsReal& _c01104,
                        RooAbsReal& _c01106,
                        RooAbsReal& _c01110,
                        RooAbsReal& _c01111,
                        RooAbsReal& _c01112,
                        RooAbsReal& _c01114,
                        RooAbsReal& _c01116,
                        RooAbsReal& _c01120,
                        RooAbsReal& _c01121,
                        RooAbsReal& _c01122,
                        RooAbsReal& _c01124,
                        RooAbsReal& _c01126,
                        RooAbsReal& _c01200,
                        RooAbsReal& _c01201,
                        RooAbsReal& _c01202,
                        RooAbsReal& _c01204,
                        RooAbsReal& _c01206,
                        RooAbsReal& _c01210,
                        RooAbsReal& _c01211,
                        RooAbsReal& _c01212,
                        RooAbsReal& _c01214,
                        RooAbsReal& _c01216,
                        RooAbsReal& _c01220,
                        RooAbsReal& _c01221,
                        RooAbsReal& _c01222,
                        RooAbsReal& _c01224,
                        RooAbsReal& _c01226,
                        RooAbsReal& _c02000,
                        RooAbsReal& _c02001,
                        RooAbsReal& _c02002,
                        RooAbsReal& _c02004,
                        RooAbsReal& _c02006,
                        RooAbsReal& _c02010,
                        RooAbsReal& _c02011,
                        RooAbsReal& _c02012,
                        RooAbsReal& _c02014,
                        RooAbsReal& _c02016,
                        RooAbsReal& _c02020,
                        RooAbsReal& _c02021,
                        RooAbsReal& _c02022,
                        RooAbsReal& _c02024,
                        RooAbsReal& _c02026,
                        RooAbsReal& _c02100,
                        RooAbsReal& _c02101,
                        RooAbsReal& _c02102,
                        RooAbsReal& _c02104,
                        RooAbsReal& _c02106,
                        RooAbsReal& _c02110,
                        RooAbsReal& _c02111,
                        RooAbsReal& _c02112,
                        RooAbsReal& _c02114,
                        RooAbsReal& _c02116,
                        RooAbsReal& _c02120,
                        RooAbsReal& _c02121,
                        RooAbsReal& _c02122,
                        RooAbsReal& _c02124,
                        RooAbsReal& _c02126,
                        RooAbsReal& _c02200,
                        RooAbsReal& _c02201,
                        RooAbsReal& _c02202,
                        RooAbsReal& _c02204,
                        RooAbsReal& _c02206,
                        RooAbsReal& _c02210,
                        RooAbsReal& _c02211,
                        RooAbsReal& _c02212,
                        RooAbsReal& _c02214,
                        RooAbsReal& _c02216,
                        RooAbsReal& _c02220,
                        RooAbsReal& _c02221,
                        RooAbsReal& _c02222,
                        RooAbsReal& _c02224,
                        RooAbsReal& _c02226,
                        RooAbsReal& _c10000,
                        RooAbsReal& _c10001,
                        RooAbsReal& _c10002,
                        RooAbsReal& _c10004,
                        RooAbsReal& _c10006,
                        RooAbsReal& _c10010,
                        RooAbsReal& _c10011,
                        RooAbsReal& _c10012,
                        RooAbsReal& _c10014,
                        RooAbsReal& _c10016,
                        RooAbsReal& _c10020,
                        RooAbsReal& _c10021,
                        RooAbsReal& _c10022,
                        RooAbsReal& _c10024,
                        RooAbsReal& _c10026,
                        RooAbsReal& _c10100,
                        RooAbsReal& _c10101,
                        RooAbsReal& _c10102,
                        RooAbsReal& _c10104,
                        RooAbsReal& _c10106,
                        RooAbsReal& _c10110,
                        RooAbsReal& _c10111,
                        RooAbsReal& _c10112,
                        RooAbsReal& _c10114,
                        RooAbsReal& _c10116,
                        RooAbsReal& _c10120,
                        RooAbsReal& _c10121,
                        RooAbsReal& _c10122,
                        RooAbsReal& _c10124,
                        RooAbsReal& _c10126,
                        RooAbsReal& _c10200,
                        RooAbsReal& _c10201,
                        RooAbsReal& _c10202,
                        RooAbsReal& _c10204,
                        RooAbsReal& _c10206,
                        RooAbsReal& _c10210,
                        RooAbsReal& _c10211,
                        RooAbsReal& _c10212,
                        RooAbsReal& _c10214,
                        RooAbsReal& _c10216,
                        RooAbsReal& _c10220,
                        RooAbsReal& _c10221,
                        RooAbsReal& _c10222,
                        RooAbsReal& _c10224,
                        RooAbsReal& _c10226,
                        RooAbsReal& _c11000,
                        RooAbsReal& _c11001,
                        RooAbsReal& _c11002,
                        RooAbsReal& _c11004,
                        RooAbsReal& _c11006,
                        RooAbsReal& _c11010,
                        RooAbsReal& _c11011,
                        RooAbsReal& _c11012,
                        RooAbsReal& _c11014,
                        RooAbsReal& _c11016,
                        RooAbsReal& _c11020,
                        RooAbsReal& _c11021,
                        RooAbsReal& _c11022,
                        RooAbsReal& _c11024,
                        RooAbsReal& _c11026,
                        RooAbsReal& _c11100,
                        RooAbsReal& _c11101,
                        RooAbsReal& _c11102,
                        RooAbsReal& _c11104,
                        RooAbsReal& _c11106,
                        RooAbsReal& _c11110,
                        RooAbsReal& _c11111,
                        RooAbsReal& _c11112,
                        RooAbsReal& _c11114,
                        RooAbsReal& _c11116,
                        RooAbsReal& _c11120,
                        RooAbsReal& _c11121,
                        RooAbsReal& _c11122,
                        RooAbsReal& _c11124,
                        RooAbsReal& _c11126,
                        RooAbsReal& _c11200,
                        RooAbsReal& _c11201,
                        RooAbsReal& _c11202,
                        RooAbsReal& _c11204,
                        RooAbsReal& _c11206,
                        RooAbsReal& _c11210,
                        RooAbsReal& _c11211,
                        RooAbsReal& _c11212,
                        RooAbsReal& _c11214,
                        RooAbsReal& _c11216,
                        RooAbsReal& _c11220,
                        RooAbsReal& _c11221,
                        RooAbsReal& _c11222,
                        RooAbsReal& _c11224,
                        RooAbsReal& _c11226,
                        RooAbsReal& _c12000,
                        RooAbsReal& _c12001,
                        RooAbsReal& _c12002,
                        RooAbsReal& _c12004,
                        RooAbsReal& _c12006,
                        RooAbsReal& _c12010,
                        RooAbsReal& _c12011,
                        RooAbsReal& _c12012,
                        RooAbsReal& _c12014,
                        RooAbsReal& _c12016,
                        RooAbsReal& _c12020,
                        RooAbsReal& _c12021,
                        RooAbsReal& _c12022,
                        RooAbsReal& _c12024,
                        RooAbsReal& _c12026,
                        RooAbsReal& _c12100,
                        RooAbsReal& _c12101,
                        RooAbsReal& _c12102,
                        RooAbsReal& _c12104,
                        RooAbsReal& _c12106,
                        RooAbsReal& _c12110,
                        RooAbsReal& _c12111,
                        RooAbsReal& _c12112,
                        RooAbsReal& _c12114,
                        RooAbsReal& _c12116,
                        RooAbsReal& _c12120,
                        RooAbsReal& _c12121,
                        RooAbsReal& _c12122,
                        RooAbsReal& _c12124,
                        RooAbsReal& _c12126,
                        RooAbsReal& _c12200,
                        RooAbsReal& _c12201,
                        RooAbsReal& _c12202,
                        RooAbsReal& _c12204,
                        RooAbsReal& _c12206,
                        RooAbsReal& _c12210,
                        RooAbsReal& _c12211,
                        RooAbsReal& _c12212,
                        RooAbsReal& _c12214,
                        RooAbsReal& _c12216,
                        RooAbsReal& _c12220,
                        RooAbsReal& _c12221,
                        RooAbsReal& _c12222,
                        RooAbsReal& _c12224,
                        RooAbsReal& _c20000,
                        RooAbsReal& _c20001,
                        RooAbsReal& _c20002,
                        RooAbsReal& _c20004,
                        RooAbsReal& _c20006,
                        RooAbsReal& _c20010,
                        RooAbsReal& _c20011,
                        RooAbsReal& _c20012,
                        RooAbsReal& _c20014,
                        RooAbsReal& _c20016,
                        RooAbsReal& _c20020,
                        RooAbsReal& _c20021,
                        RooAbsReal& _c20022,
                        RooAbsReal& _c20024,
                        RooAbsReal& _c20026,
                        RooAbsReal& _c20100,
                        RooAbsReal& _c20101,
                        RooAbsReal& _c20102,
                        RooAbsReal& _c20104,
                        RooAbsReal& _c20106,
                        RooAbsReal& _c20110,
                        RooAbsReal& _c20111,
                        RooAbsReal& _c20112,
                        RooAbsReal& _c20114,
                        RooAbsReal& _c20116,
                        RooAbsReal& _c20120,
                        RooAbsReal& _c20121,
                        RooAbsReal& _c20122,
                        RooAbsReal& _c20124,
                        RooAbsReal& _c20126,
                        RooAbsReal& _c20200,
                        RooAbsReal& _c20201,
                        RooAbsReal& _c20202,
                        RooAbsReal& _c20204,
                        RooAbsReal& _c20206,
                        RooAbsReal& _c20210,
                        RooAbsReal& _c20211,
                        RooAbsReal& _c20212,
                        RooAbsReal& _c20214,
                        RooAbsReal& _c20216,
                        RooAbsReal& _c20220,
                        RooAbsReal& _c20221,
                        RooAbsReal& _c20222,
                        RooAbsReal& _c20224,
                        RooAbsReal& _c20226,
                        RooAbsReal& _c21000,
                        RooAbsReal& _c21001,
                        RooAbsReal& _c21002,
                        RooAbsReal& _c21004,
                        RooAbsReal& _c21006,
                        RooAbsReal& _c21010,
                        RooAbsReal& _c21011,
                        RooAbsReal& _c21012,
                        RooAbsReal& _c21014,
                        RooAbsReal& _c21016,
                        RooAbsReal& _c21020,
                        RooAbsReal& _c21021,
                        RooAbsReal& _c21022,
                        RooAbsReal& _c21024,
                        RooAbsReal& _c21026,
                        RooAbsReal& _c21100,
                        RooAbsReal& _c21101,
                        RooAbsReal& _c21102,
                        RooAbsReal& _c21104,
                        RooAbsReal& _c21106,
                        RooAbsReal& _c21110,
                        RooAbsReal& _c21111,
                        RooAbsReal& _c21112,
                        RooAbsReal& _c21114,
                        RooAbsReal& _c21116,
                        RooAbsReal& _c21120,
                        RooAbsReal& _c21121,
                        RooAbsReal& _c21122,
                        RooAbsReal& _c21124,
                        RooAbsReal& _c21126,
                        RooAbsReal& _c21200,
                        RooAbsReal& _c21201,
                        RooAbsReal& _c21202,
                        RooAbsReal& _c21204,
                        RooAbsReal& _c21206,
                        RooAbsReal& _c21210,
                        RooAbsReal& _c21211,
                        RooAbsReal& _c21212,
                        RooAbsReal& _c21214,
                        RooAbsReal& _c21216,
                        RooAbsReal& _c21220,
                        RooAbsReal& _c21221,
                        RooAbsReal& _c21222,
                        RooAbsReal& _c21224,
                        RooAbsReal& _c22000,
                        RooAbsReal& _c22001,
                        RooAbsReal& _c22002,
                        RooAbsReal& _c22004,
                        RooAbsReal& _c22006,
                        RooAbsReal& _c22010,
                        RooAbsReal& _c22011,
                        RooAbsReal& _c22012,
                        RooAbsReal& _c22014,
                        RooAbsReal& _c22016,
                        RooAbsReal& _c22020,
                        RooAbsReal& _c22021,
                        RooAbsReal& _c22022,
                        RooAbsReal& _c22024,
                        RooAbsReal& _c22026,
                        RooAbsReal& _c22100,
                        RooAbsReal& _c22101,
                        RooAbsReal& _c22102,
                        RooAbsReal& _c22104,
                        RooAbsReal& _c22106,
                        RooAbsReal& _c22110,
                        RooAbsReal& _c22111,
                        RooAbsReal& _c22112,
                        RooAbsReal& _c22114,
                        RooAbsReal& _c22116,
                        RooAbsReal& _c22120,
                        RooAbsReal& _c22121,
                        RooAbsReal& _c22122,
                        RooAbsReal& _c22124,
                        RooAbsReal& _c22200,
                        RooAbsReal& _c22201,
                        RooAbsReal& _c22202,
                        RooAbsReal& _c22204,
                        RooAbsReal& _c22206,
                        RooAbsReal& _c22210,
                        RooAbsReal& _c22211,
                        RooAbsReal& _c22212,
                        RooAbsReal& _c22214,
                        RooAbsReal& _c22220,
                        RooAbsReal& _c22221,
                        RooAbsReal& _c22222,
                        RooAbsReal& _c22224) :
   RooAbsPdf(name,title), 
   costheta0("costheta0","costheta0",this,_costheta0),
   costheta1("costheta1","costheta1",this,_costheta1),
   costheta2("costheta2","costheta2",this,_costheta2),
   phi1("phi1","phi1",this,_phi1),
   phi2("phi2","phi2",this,_phi2),
   c00000("c00000","c00000",this,_c00000),
   c00001("c00001","c00001",this,_c00001),
   c00002("c00002","c00002",this,_c00002),
   c00004("c00004","c00004",this,_c00004),
   c00006("c00006","c00006",this,_c00006),
   c00010("c00010","c00010",this,_c00010),
   c00011("c00011","c00011",this,_c00011),
   c00012("c00012","c00012",this,_c00012),
   c00014("c00014","c00014",this,_c00014),
   c00016("c00016","c00016",this,_c00016),
   c00020("c00020","c00020",this,_c00020),
   c00021("c00021","c00021",this,_c00021),
   c00022("c00022","c00022",this,_c00022),
   c00024("c00024","c00024",this,_c00024),
   c00026("c00026","c00026",this,_c00026),
   c00100("c00100","c00100",this,_c00100),
   c00101("c00101","c00101",this,_c00101),
   c00102("c00102","c00102",this,_c00102),
   c00104("c00104","c00104",this,_c00104),
   c00106("c00106","c00106",this,_c00106),
   c00110("c00110","c00110",this,_c00110),
   c00111("c00111","c00111",this,_c00111),
   c00112("c00112","c00112",this,_c00112),
   c00114("c00114","c00114",this,_c00114),
   c00116("c00116","c00116",this,_c00116),
   c00120("c00120","c00120",this,_c00120),
   c00121("c00121","c00121",this,_c00121),
   c00122("c00122","c00122",this,_c00122),
   c00124("c00124","c00124",this,_c00124),
   c00126("c00126","c00126",this,_c00126),
   c00200("c00200","c00200",this,_c00200),
   c00201("c00201","c00201",this,_c00201),
   c00202("c00202","c00202",this,_c00202),
   c00204("c00204","c00204",this,_c00204),
   c00206("c00206","c00206",this,_c00206),
   c00210("c00210","c00210",this,_c00210),
   c00211("c00211","c00211",this,_c00211),
   c00212("c00212","c00212",this,_c00212),
   c00214("c00214","c00214",this,_c00214),
   c00216("c00216","c00216",this,_c00216),
   c00220("c00220","c00220",this,_c00220),
   c00221("c00221","c00221",this,_c00221),
   c00222("c00222","c00222",this,_c00222),
   c00224("c00224","c00224",this,_c00224),
   c00226("c00226","c00226",this,_c00226),
   c01000("c01000","c01000",this,_c01000),
   c01001("c01001","c01001",this,_c01001),
   c01002("c01002","c01002",this,_c01002),
   c01004("c01004","c01004",this,_c01004),
   c01006("c01006","c01006",this,_c01006),
   c01010("c01010","c01010",this,_c01010),
   c01011("c01011","c01011",this,_c01011),
   c01012("c01012","c01012",this,_c01012),
   c01014("c01014","c01014",this,_c01014),
   c01016("c01016","c01016",this,_c01016),
   c01020("c01020","c01020",this,_c01020),
   c01021("c01021","c01021",this,_c01021),
   c01022("c01022","c01022",this,_c01022),
   c01024("c01024","c01024",this,_c01024),
   c01026("c01026","c01026",this,_c01026),
   c01100("c01100","c01100",this,_c01100),
   c01101("c01101","c01101",this,_c01101),
   c01102("c01102","c01102",this,_c01102),
   c01104("c01104","c01104",this,_c01104),
   c01106("c01106","c01106",this,_c01106),
   c01110("c01110","c01110",this,_c01110),
   c01111("c01111","c01111",this,_c01111),
   c01112("c01112","c01112",this,_c01112),
   c01114("c01114","c01114",this,_c01114),
   c01116("c01116","c01116",this,_c01116),
   c01120("c01120","c01120",this,_c01120),
   c01121("c01121","c01121",this,_c01121),
   c01122("c01122","c01122",this,_c01122),
   c01124("c01124","c01124",this,_c01124),
   c01126("c01126","c01126",this,_c01126),
   c01200("c01200","c01200",this,_c01200),
   c01201("c01201","c01201",this,_c01201),
   c01202("c01202","c01202",this,_c01202),
   c01204("c01204","c01204",this,_c01204),
   c01206("c01206","c01206",this,_c01206),
   c01210("c01210","c01210",this,_c01210),
   c01211("c01211","c01211",this,_c01211),
   c01212("c01212","c01212",this,_c01212),
   c01214("c01214","c01214",this,_c01214),
   c01216("c01216","c01216",this,_c01216),
   c01220("c01220","c01220",this,_c01220),
   c01221("c01221","c01221",this,_c01221),
   c01222("c01222","c01222",this,_c01222),
   c01224("c01224","c01224",this,_c01224),
   c01226("c01226","c01226",this,_c01226),
   c02000("c02000","c02000",this,_c02000),
   c02001("c02001","c02001",this,_c02001),
   c02002("c02002","c02002",this,_c02002),
   c02004("c02004","c02004",this,_c02004),
   c02006("c02006","c02006",this,_c02006),
   c02010("c02010","c02010",this,_c02010),
   c02011("c02011","c02011",this,_c02011),
   c02012("c02012","c02012",this,_c02012),
   c02014("c02014","c02014",this,_c02014),
   c02016("c02016","c02016",this,_c02016),
   c02020("c02020","c02020",this,_c02020),
   c02021("c02021","c02021",this,_c02021),
   c02022("c02022","c02022",this,_c02022),
   c02024("c02024","c02024",this,_c02024),
   c02026("c02026","c02026",this,_c02026),
   c02100("c02100","c02100",this,_c02100),
   c02101("c02101","c02101",this,_c02101),
   c02102("c02102","c02102",this,_c02102),
   c02104("c02104","c02104",this,_c02104),
   c02106("c02106","c02106",this,_c02106),
   c02110("c02110","c02110",this,_c02110),
   c02111("c02111","c02111",this,_c02111),
   c02112("c02112","c02112",this,_c02112),
   c02114("c02114","c02114",this,_c02114),
   c02116("c02116","c02116",this,_c02116),
   c02120("c02120","c02120",this,_c02120),
   c02121("c02121","c02121",this,_c02121),
   c02122("c02122","c02122",this,_c02122),
   c02124("c02124","c02124",this,_c02124),
   c02126("c02126","c02126",this,_c02126),
   c02200("c02200","c02200",this,_c02200),
   c02201("c02201","c02201",this,_c02201),
   c02202("c02202","c02202",this,_c02202),
   c02204("c02204","c02204",this,_c02204),
   c02206("c02206","c02206",this,_c02206),
   c02210("c02210","c02210",this,_c02210),
   c02211("c02211","c02211",this,_c02211),
   c02212("c02212","c02212",this,_c02212),
   c02214("c02214","c02214",this,_c02214),
   c02216("c02216","c02216",this,_c02216),
   c02220("c02220","c02220",this,_c02220),
   c02221("c02221","c02221",this,_c02221),
   c02222("c02222","c02222",this,_c02222),
   c02224("c02224","c02224",this,_c02224),
   c02226("c02226","c02226",this,_c02226),
   c10000("c10000","c10000",this,_c10000),
   c10001("c10001","c10001",this,_c10001),
   c10002("c10002","c10002",this,_c10002),
   c10004("c10004","c10004",this,_c10004),
   c10006("c10006","c10006",this,_c10006),
   c10010("c10010","c10010",this,_c10010),
   c10011("c10011","c10011",this,_c10011),
   c10012("c10012","c10012",this,_c10012),
   c10014("c10014","c10014",this,_c10014),
   c10016("c10016","c10016",this,_c10016),
   c10020("c10020","c10020",this,_c10020),
   c10021("c10021","c10021",this,_c10021),
   c10022("c10022","c10022",this,_c10022),
   c10024("c10024","c10024",this,_c10024),
   c10026("c10026","c10026",this,_c10026),
   c10100("c10100","c10100",this,_c10100),
   c10101("c10101","c10101",this,_c10101),
   c10102("c10102","c10102",this,_c10102),
   c10104("c10104","c10104",this,_c10104),
   c10106("c10106","c10106",this,_c10106),
   c10110("c10110","c10110",this,_c10110),
   c10111("c10111","c10111",this,_c10111),
   c10112("c10112","c10112",this,_c10112),
   c10114("c10114","c10114",this,_c10114),
   c10116("c10116","c10116",this,_c10116),
   c10120("c10120","c10120",this,_c10120),
   c10121("c10121","c10121",this,_c10121),
   c10122("c10122","c10122",this,_c10122),
   c10124("c10124","c10124",this,_c10124),
   c10126("c10126","c10126",this,_c10126),
   c10200("c10200","c10200",this,_c10200),
   c10201("c10201","c10201",this,_c10201),
   c10202("c10202","c10202",this,_c10202),
   c10204("c10204","c10204",this,_c10204),
   c10206("c10206","c10206",this,_c10206),
   c10210("c10210","c10210",this,_c10210),
   c10211("c10211","c10211",this,_c10211),
   c10212("c10212","c10212",this,_c10212),
   c10214("c10214","c10214",this,_c10214),
   c10216("c10216","c10216",this,_c10216),
   c10220("c10220","c10220",this,_c10220),
   c10221("c10221","c10221",this,_c10221),
   c10222("c10222","c10222",this,_c10222),
   c10224("c10224","c10224",this,_c10224),
   c10226("c10226","c10226",this,_c10226),
   c11000("c11000","c11000",this,_c11000),
   c11001("c11001","c11001",this,_c11001),
   c11002("c11002","c11002",this,_c11002),
   c11004("c11004","c11004",this,_c11004),
   c11006("c11006","c11006",this,_c11006),
   c11010("c11010","c11010",this,_c11010),
   c11011("c11011","c11011",this,_c11011),
   c11012("c11012","c11012",this,_c11012),
   c11014("c11014","c11014",this,_c11014),
   c11016("c11016","c11016",this,_c11016),
   c11020("c11020","c11020",this,_c11020),
   c11021("c11021","c11021",this,_c11021),
   c11022("c11022","c11022",this,_c11022),
   c11024("c11024","c11024",this,_c11024),
   c11026("c11026","c11026",this,_c11026),
   c11100("c11100","c11100",this,_c11100),
   c11101("c11101","c11101",this,_c11101),
   c11102("c11102","c11102",this,_c11102),
   c11104("c11104","c11104",this,_c11104),
   c11106("c11106","c11106",this,_c11106),
   c11110("c11110","c11110",this,_c11110),
   c11111("c11111","c11111",this,_c11111),
   c11112("c11112","c11112",this,_c11112),
   c11114("c11114","c11114",this,_c11114),
   c11116("c11116","c11116",this,_c11116),
   c11120("c11120","c11120",this,_c11120),
   c11121("c11121","c11121",this,_c11121),
   c11122("c11122","c11122",this,_c11122),
   c11124("c11124","c11124",this,_c11124),
   c11126("c11126","c11126",this,_c11126),
   c11200("c11200","c11200",this,_c11200),
   c11201("c11201","c11201",this,_c11201),
   c11202("c11202","c11202",this,_c11202),
   c11204("c11204","c11204",this,_c11204),
   c11206("c11206","c11206",this,_c11206),
   c11210("c11210","c11210",this,_c11210),
   c11211("c11211","c11211",this,_c11211),
   c11212("c11212","c11212",this,_c11212),
   c11214("c11214","c11214",this,_c11214),
   c11216("c11216","c11216",this,_c11216),
   c11220("c11220","c11220",this,_c11220),
   c11221("c11221","c11221",this,_c11221),
   c11222("c11222","c11222",this,_c11222),
   c11224("c11224","c11224",this,_c11224),
   c11226("c11226","c11226",this,_c11226),
   c12000("c12000","c12000",this,_c12000),
   c12001("c12001","c12001",this,_c12001),
   c12002("c12002","c12002",this,_c12002),
   c12004("c12004","c12004",this,_c12004),
   c12006("c12006","c12006",this,_c12006),
   c12010("c12010","c12010",this,_c12010),
   c12011("c12011","c12011",this,_c12011),
   c12012("c12012","c12012",this,_c12012),
   c12014("c12014","c12014",this,_c12014),
   c12016("c12016","c12016",this,_c12016),
   c12020("c12020","c12020",this,_c12020),
   c12021("c12021","c12021",this,_c12021),
   c12022("c12022","c12022",this,_c12022),
   c12024("c12024","c12024",this,_c12024),
   c12026("c12026","c12026",this,_c12026),
   c12100("c12100","c12100",this,_c12100),
   c12101("c12101","c12101",this,_c12101),
   c12102("c12102","c12102",this,_c12102),
   c12104("c12104","c12104",this,_c12104),
   c12106("c12106","c12106",this,_c12106),
   c12110("c12110","c12110",this,_c12110),
   c12111("c12111","c12111",this,_c12111),
   c12112("c12112","c12112",this,_c12112),
   c12114("c12114","c12114",this,_c12114),
   c12116("c12116","c12116",this,_c12116),
   c12120("c12120","c12120",this,_c12120),
   c12121("c12121","c12121",this,_c12121),
   c12122("c12122","c12122",this,_c12122),
   c12124("c12124","c12124",this,_c12124),
   c12126("c12126","c12126",this,_c12126),
   c12200("c12200","c12200",this,_c12200),
   c12201("c12201","c12201",this,_c12201),
   c12202("c12202","c12202",this,_c12202),
   c12204("c12204","c12204",this,_c12204),
   c12206("c12206","c12206",this,_c12206),
   c12210("c12210","c12210",this,_c12210),
   c12211("c12211","c12211",this,_c12211),
   c12212("c12212","c12212",this,_c12212),
   c12214("c12214","c12214",this,_c12214),
   c12216("c12216","c12216",this,_c12216),
   c12220("c12220","c12220",this,_c12220),
   c12221("c12221","c12221",this,_c12221),
   c12222("c12222","c12222",this,_c12222),
   c12224("c12224","c12224",this,_c12224),
   c20000("c20000","c20000",this,_c20000),
   c20001("c20001","c20001",this,_c20001),
   c20002("c20002","c20002",this,_c20002),
   c20004("c20004","c20004",this,_c20004),
   c20006("c20006","c20006",this,_c20006),
   c20010("c20010","c20010",this,_c20010),
   c20011("c20011","c20011",this,_c20011),
   c20012("c20012","c20012",this,_c20012),
   c20014("c20014","c20014",this,_c20014),
   c20016("c20016","c20016",this,_c20016),
   c20020("c20020","c20020",this,_c20020),
   c20021("c20021","c20021",this,_c20021),
   c20022("c20022","c20022",this,_c20022),
   c20024("c20024","c20024",this,_c20024),
   c20026("c20026","c20026",this,_c20026),
   c20100("c20100","c20100",this,_c20100),
   c20101("c20101","c20101",this,_c20101),
   c20102("c20102","c20102",this,_c20102),
   c20104("c20104","c20104",this,_c20104),
   c20106("c20106","c20106",this,_c20106),
   c20110("c20110","c20110",this,_c20110),
   c20111("c20111","c20111",this,_c20111),
   c20112("c20112","c20112",this,_c20112),
   c20114("c20114","c20114",this,_c20114),
   c20116("c20116","c20116",this,_c20116),
   c20120("c20120","c20120",this,_c20120),
   c20121("c20121","c20121",this,_c20121),
   c20122("c20122","c20122",this,_c20122),
   c20124("c20124","c20124",this,_c20124),
   c20126("c20126","c20126",this,_c20126),
   c20200("c20200","c20200",this,_c20200),
   c20201("c20201","c20201",this,_c20201),
   c20202("c20202","c20202",this,_c20202),
   c20204("c20204","c20204",this,_c20204),
   c20206("c20206","c20206",this,_c20206),
   c20210("c20210","c20210",this,_c20210),
   c20211("c20211","c20211",this,_c20211),
   c20212("c20212","c20212",this,_c20212),
   c20214("c20214","c20214",this,_c20214),
   c20216("c20216","c20216",this,_c20216),
   c20220("c20220","c20220",this,_c20220),
   c20221("c20221","c20221",this,_c20221),
   c20222("c20222","c20222",this,_c20222),
   c20224("c20224","c20224",this,_c20224),
   c20226("c20226","c20226",this,_c20226),
   c21000("c21000","c21000",this,_c21000),
   c21001("c21001","c21001",this,_c21001),
   c21002("c21002","c21002",this,_c21002),
   c21004("c21004","c21004",this,_c21004),
   c21006("c21006","c21006",this,_c21006),
   c21010("c21010","c21010",this,_c21010),
   c21011("c21011","c21011",this,_c21011),
   c21012("c21012","c21012",this,_c21012),
   c21014("c21014","c21014",this,_c21014),
   c21016("c21016","c21016",this,_c21016),
   c21020("c21020","c21020",this,_c21020),
   c21021("c21021","c21021",this,_c21021),
   c21022("c21022","c21022",this,_c21022),
   c21024("c21024","c21024",this,_c21024),
   c21026("c21026","c21026",this,_c21026),
   c21100("c21100","c21100",this,_c21100),
   c21101("c21101","c21101",this,_c21101),
   c21102("c21102","c21102",this,_c21102),
   c21104("c21104","c21104",this,_c21104),
   c21106("c21106","c21106",this,_c21106),
   c21110("c21110","c21110",this,_c21110),
   c21111("c21111","c21111",this,_c21111),
   c21112("c21112","c21112",this,_c21112),
   c21114("c21114","c21114",this,_c21114),
   c21116("c21116","c21116",this,_c21116),
   c21120("c21120","c21120",this,_c21120),
   c21121("c21121","c21121",this,_c21121),
   c21122("c21122","c21122",this,_c21122),
   c21124("c21124","c21124",this,_c21124),
   c21126("c21126","c21126",this,_c21126),
   c21200("c21200","c21200",this,_c21200),
   c21201("c21201","c21201",this,_c21201),
   c21202("c21202","c21202",this,_c21202),
   c21204("c21204","c21204",this,_c21204),
   c21206("c21206","c21206",this,_c21206),
   c21210("c21210","c21210",this,_c21210),
   c21211("c21211","c21211",this,_c21211),
   c21212("c21212","c21212",this,_c21212),
   c21214("c21214","c21214",this,_c21214),
   c21216("c21216","c21216",this,_c21216),
   c21220("c21220","c21220",this,_c21220),
   c21221("c21221","c21221",this,_c21221),
   c21222("c21222","c21222",this,_c21222),
   c21224("c21224","c21224",this,_c21224),
   c22000("c22000","c22000",this,_c22000),
   c22001("c22001","c22001",this,_c22001),
   c22002("c22002","c22002",this,_c22002),
   c22004("c22004","c22004",this,_c22004),
   c22006("c22006","c22006",this,_c22006),
   c22010("c22010","c22010",this,_c22010),
   c22011("c22011","c22011",this,_c22011),
   c22012("c22012","c22012",this,_c22012),
   c22014("c22014","c22014",this,_c22014),
   c22016("c22016","c22016",this,_c22016),
   c22020("c22020","c22020",this,_c22020),
   c22021("c22021","c22021",this,_c22021),
   c22022("c22022","c22022",this,_c22022),
   c22024("c22024","c22024",this,_c22024),
   c22026("c22026","c22026",this,_c22026),
   c22100("c22100","c22100",this,_c22100),
   c22101("c22101","c22101",this,_c22101),
   c22102("c22102","c22102",this,_c22102),
   c22104("c22104","c22104",this,_c22104),
   c22106("c22106","c22106",this,_c22106),
   c22110("c22110","c22110",this,_c22110),
   c22111("c22111","c22111",this,_c22111),
   c22112("c22112","c22112",this,_c22112),
   c22114("c22114","c22114",this,_c22114),
   c22116("c22116","c22116",this,_c22116),
   c22120("c22120","c22120",this,_c22120),
   c22121("c22121","c22121",this,_c22121),
   c22122("c22122","c22122",this,_c22122),
   c22124("c22124","c22124",this,_c22124),
   c22200("c22200","c22200",this,_c22200),
   c22201("c22201","c22201",this,_c22201),
   c22202("c22202","c22202",this,_c22202),
   c22204("c22204","c22204",this,_c22204),
   c22206("c22206","c22206",this,_c22206),
   c22210("c22210","c22210",this,_c22210),
   c22211("c22211","c22211",this,_c22211),
   c22212("c22212","c22212",this,_c22212),
   c22214("c22214","c22214",this,_c22214),
   c22220("c22220","c22220",this,_c22220),
   c22221("c22221","c22221",this,_c22221),
   c22222("c22222","c22222",this,_c22222),
   c22224("c22224","c22224",this,_c22224)
 { 
 } 


 RooLegendre5Pdf::RooLegendre5Pdf(const RooLegendre5Pdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   costheta0("costheta0",this,other.costheta0),
   costheta1("costheta1",this,other.costheta1),
   costheta2("costheta2",this,other.costheta2),
   phi1("phi1",this,other.phi1),
   phi2("phi2",this,other.phi2),
   c00000("c00000",this,other.c00000),
   c00001("c00001",this,other.c00001),
   c00002("c00002",this,other.c00002),
   c00004("c00004",this,other.c00004),
   c00006("c00006",this,other.c00006),
   c00010("c00010",this,other.c00010),
   c00011("c00011",this,other.c00011),
   c00012("c00012",this,other.c00012),
   c00014("c00014",this,other.c00014),
   c00016("c00016",this,other.c00016),
   c00020("c00020",this,other.c00020),
   c00021("c00021",this,other.c00021),
   c00022("c00022",this,other.c00022),
   c00024("c00024",this,other.c00024),
   c00026("c00026",this,other.c00026),
   c00100("c00100",this,other.c00100),
   c00101("c00101",this,other.c00101),
   c00102("c00102",this,other.c00102),
   c00104("c00104",this,other.c00104),
   c00106("c00106",this,other.c00106),
   c00110("c00110",this,other.c00110),
   c00111("c00111",this,other.c00111),
   c00112("c00112",this,other.c00112),
   c00114("c00114",this,other.c00114),
   c00116("c00116",this,other.c00116),
   c00120("c00120",this,other.c00120),
   c00121("c00121",this,other.c00121),
   c00122("c00122",this,other.c00122),
   c00124("c00124",this,other.c00124),
   c00126("c00126",this,other.c00126),
   c00200("c00200",this,other.c00200),
   c00201("c00201",this,other.c00201),
   c00202("c00202",this,other.c00202),
   c00204("c00204",this,other.c00204),
   c00206("c00206",this,other.c00206),
   c00210("c00210",this,other.c00210),
   c00211("c00211",this,other.c00211),
   c00212("c00212",this,other.c00212),
   c00214("c00214",this,other.c00214),
   c00216("c00216",this,other.c00216),
   c00220("c00220",this,other.c00220),
   c00221("c00221",this,other.c00221),
   c00222("c00222",this,other.c00222),
   c00224("c00224",this,other.c00224),
   c00226("c00226",this,other.c00226),
   c01000("c01000",this,other.c01000),
   c01001("c01001",this,other.c01001),
   c01002("c01002",this,other.c01002),
   c01004("c01004",this,other.c01004),
   c01006("c01006",this,other.c01006),
   c01010("c01010",this,other.c01010),
   c01011("c01011",this,other.c01011),
   c01012("c01012",this,other.c01012),
   c01014("c01014",this,other.c01014),
   c01016("c01016",this,other.c01016),
   c01020("c01020",this,other.c01020),
   c01021("c01021",this,other.c01021),
   c01022("c01022",this,other.c01022),
   c01024("c01024",this,other.c01024),
   c01026("c01026",this,other.c01026),
   c01100("c01100",this,other.c01100),
   c01101("c01101",this,other.c01101),
   c01102("c01102",this,other.c01102),
   c01104("c01104",this,other.c01104),
   c01106("c01106",this,other.c01106),
   c01110("c01110",this,other.c01110),
   c01111("c01111",this,other.c01111),
   c01112("c01112",this,other.c01112),
   c01114("c01114",this,other.c01114),
   c01116("c01116",this,other.c01116),
   c01120("c01120",this,other.c01120),
   c01121("c01121",this,other.c01121),
   c01122("c01122",this,other.c01122),
   c01124("c01124",this,other.c01124),
   c01126("c01126",this,other.c01126),
   c01200("c01200",this,other.c01200),
   c01201("c01201",this,other.c01201),
   c01202("c01202",this,other.c01202),
   c01204("c01204",this,other.c01204),
   c01206("c01206",this,other.c01206),
   c01210("c01210",this,other.c01210),
   c01211("c01211",this,other.c01211),
   c01212("c01212",this,other.c01212),
   c01214("c01214",this,other.c01214),
   c01216("c01216",this,other.c01216),
   c01220("c01220",this,other.c01220),
   c01221("c01221",this,other.c01221),
   c01222("c01222",this,other.c01222),
   c01224("c01224",this,other.c01224),
   c01226("c01226",this,other.c01226),
   c02000("c02000",this,other.c02000),
   c02001("c02001",this,other.c02001),
   c02002("c02002",this,other.c02002),
   c02004("c02004",this,other.c02004),
   c02006("c02006",this,other.c02006),
   c02010("c02010",this,other.c02010),
   c02011("c02011",this,other.c02011),
   c02012("c02012",this,other.c02012),
   c02014("c02014",this,other.c02014),
   c02016("c02016",this,other.c02016),
   c02020("c02020",this,other.c02020),
   c02021("c02021",this,other.c02021),
   c02022("c02022",this,other.c02022),
   c02024("c02024",this,other.c02024),
   c02026("c02026",this,other.c02026),
   c02100("c02100",this,other.c02100),
   c02101("c02101",this,other.c02101),
   c02102("c02102",this,other.c02102),
   c02104("c02104",this,other.c02104),
   c02106("c02106",this,other.c02106),
   c02110("c02110",this,other.c02110),
   c02111("c02111",this,other.c02111),
   c02112("c02112",this,other.c02112),
   c02114("c02114",this,other.c02114),
   c02116("c02116",this,other.c02116),
   c02120("c02120",this,other.c02120),
   c02121("c02121",this,other.c02121),
   c02122("c02122",this,other.c02122),
   c02124("c02124",this,other.c02124),
   c02126("c02126",this,other.c02126),
   c02200("c02200",this,other.c02200),
   c02201("c02201",this,other.c02201),
   c02202("c02202",this,other.c02202),
   c02204("c02204",this,other.c02204),
   c02206("c02206",this,other.c02206),
   c02210("c02210",this,other.c02210),
   c02211("c02211",this,other.c02211),
   c02212("c02212",this,other.c02212),
   c02214("c02214",this,other.c02214),
   c02216("c02216",this,other.c02216),
   c02220("c02220",this,other.c02220),
   c02221("c02221",this,other.c02221),
   c02222("c02222",this,other.c02222),
   c02224("c02224",this,other.c02224),
   c02226("c02226",this,other.c02226),
   c10000("c10000",this,other.c10000),
   c10001("c10001",this,other.c10001),
   c10002("c10002",this,other.c10002),
   c10004("c10004",this,other.c10004),
   c10006("c10006",this,other.c10006),
   c10010("c10010",this,other.c10010),
   c10011("c10011",this,other.c10011),
   c10012("c10012",this,other.c10012),
   c10014("c10014",this,other.c10014),
   c10016("c10016",this,other.c10016),
   c10020("c10020",this,other.c10020),
   c10021("c10021",this,other.c10021),
   c10022("c10022",this,other.c10022),
   c10024("c10024",this,other.c10024),
   c10026("c10026",this,other.c10026),
   c10100("c10100",this,other.c10100),
   c10101("c10101",this,other.c10101),
   c10102("c10102",this,other.c10102),
   c10104("c10104",this,other.c10104),
   c10106("c10106",this,other.c10106),
   c10110("c10110",this,other.c10110),
   c10111("c10111",this,other.c10111),
   c10112("c10112",this,other.c10112),
   c10114("c10114",this,other.c10114),
   c10116("c10116",this,other.c10116),
   c10120("c10120",this,other.c10120),
   c10121("c10121",this,other.c10121),
   c10122("c10122",this,other.c10122),
   c10124("c10124",this,other.c10124),
   c10126("c10126",this,other.c10126),
   c10200("c10200",this,other.c10200),
   c10201("c10201",this,other.c10201),
   c10202("c10202",this,other.c10202),
   c10204("c10204",this,other.c10204),
   c10206("c10206",this,other.c10206),
   c10210("c10210",this,other.c10210),
   c10211("c10211",this,other.c10211),
   c10212("c10212",this,other.c10212),
   c10214("c10214",this,other.c10214),
   c10216("c10216",this,other.c10216),
   c10220("c10220",this,other.c10220),
   c10221("c10221",this,other.c10221),
   c10222("c10222",this,other.c10222),
   c10224("c10224",this,other.c10224),
   c10226("c10226",this,other.c10226),
   c11000("c11000",this,other.c11000),
   c11001("c11001",this,other.c11001),
   c11002("c11002",this,other.c11002),
   c11004("c11004",this,other.c11004),
   c11006("c11006",this,other.c11006),
   c11010("c11010",this,other.c11010),
   c11011("c11011",this,other.c11011),
   c11012("c11012",this,other.c11012),
   c11014("c11014",this,other.c11014),
   c11016("c11016",this,other.c11016),
   c11020("c11020",this,other.c11020),
   c11021("c11021",this,other.c11021),
   c11022("c11022",this,other.c11022),
   c11024("c11024",this,other.c11024),
   c11026("c11026",this,other.c11026),
   c11100("c11100",this,other.c11100),
   c11101("c11101",this,other.c11101),
   c11102("c11102",this,other.c11102),
   c11104("c11104",this,other.c11104),
   c11106("c11106",this,other.c11106),
   c11110("c11110",this,other.c11110),
   c11111("c11111",this,other.c11111),
   c11112("c11112",this,other.c11112),
   c11114("c11114",this,other.c11114),
   c11116("c11116",this,other.c11116),
   c11120("c11120",this,other.c11120),
   c11121("c11121",this,other.c11121),
   c11122("c11122",this,other.c11122),
   c11124("c11124",this,other.c11124),
   c11126("c11126",this,other.c11126),
   c11200("c11200",this,other.c11200),
   c11201("c11201",this,other.c11201),
   c11202("c11202",this,other.c11202),
   c11204("c11204",this,other.c11204),
   c11206("c11206",this,other.c11206),
   c11210("c11210",this,other.c11210),
   c11211("c11211",this,other.c11211),
   c11212("c11212",this,other.c11212),
   c11214("c11214",this,other.c11214),
   c11216("c11216",this,other.c11216),
   c11220("c11220",this,other.c11220),
   c11221("c11221",this,other.c11221),
   c11222("c11222",this,other.c11222),
   c11224("c11224",this,other.c11224),
   c11226("c11226",this,other.c11226),
   c12000("c12000",this,other.c12000),
   c12001("c12001",this,other.c12001),
   c12002("c12002",this,other.c12002),
   c12004("c12004",this,other.c12004),
   c12006("c12006",this,other.c12006),
   c12010("c12010",this,other.c12010),
   c12011("c12011",this,other.c12011),
   c12012("c12012",this,other.c12012),
   c12014("c12014",this,other.c12014),
   c12016("c12016",this,other.c12016),
   c12020("c12020",this,other.c12020),
   c12021("c12021",this,other.c12021),
   c12022("c12022",this,other.c12022),
   c12024("c12024",this,other.c12024),
   c12026("c12026",this,other.c12026),
   c12100("c12100",this,other.c12100),
   c12101("c12101",this,other.c12101),
   c12102("c12102",this,other.c12102),
   c12104("c12104",this,other.c12104),
   c12106("c12106",this,other.c12106),
   c12110("c12110",this,other.c12110),
   c12111("c12111",this,other.c12111),
   c12112("c12112",this,other.c12112),
   c12114("c12114",this,other.c12114),
   c12116("c12116",this,other.c12116),
   c12120("c12120",this,other.c12120),
   c12121("c12121",this,other.c12121),
   c12122("c12122",this,other.c12122),
   c12124("c12124",this,other.c12124),
   c12126("c12126",this,other.c12126),
   c12200("c12200",this,other.c12200),
   c12201("c12201",this,other.c12201),
   c12202("c12202",this,other.c12202),
   c12204("c12204",this,other.c12204),
   c12206("c12206",this,other.c12206),
   c12210("c12210",this,other.c12210),
   c12211("c12211",this,other.c12211),
   c12212("c12212",this,other.c12212),
   c12214("c12214",this,other.c12214),
   c12216("c12216",this,other.c12216),
   c12220("c12220",this,other.c12220),
   c12221("c12221",this,other.c12221),
   c12222("c12222",this,other.c12222),
   c12224("c12224",this,other.c12224),
   c20000("c20000",this,other.c20000),
   c20001("c20001",this,other.c20001),
   c20002("c20002",this,other.c20002),
   c20004("c20004",this,other.c20004),
   c20006("c20006",this,other.c20006),
   c20010("c20010",this,other.c20010),
   c20011("c20011",this,other.c20011),
   c20012("c20012",this,other.c20012),
   c20014("c20014",this,other.c20014),
   c20016("c20016",this,other.c20016),
   c20020("c20020",this,other.c20020),
   c20021("c20021",this,other.c20021),
   c20022("c20022",this,other.c20022),
   c20024("c20024",this,other.c20024),
   c20026("c20026",this,other.c20026),
   c20100("c20100",this,other.c20100),
   c20101("c20101",this,other.c20101),
   c20102("c20102",this,other.c20102),
   c20104("c20104",this,other.c20104),
   c20106("c20106",this,other.c20106),
   c20110("c20110",this,other.c20110),
   c20111("c20111",this,other.c20111),
   c20112("c20112",this,other.c20112),
   c20114("c20114",this,other.c20114),
   c20116("c20116",this,other.c20116),
   c20120("c20120",this,other.c20120),
   c20121("c20121",this,other.c20121),
   c20122("c20122",this,other.c20122),
   c20124("c20124",this,other.c20124),
   c20126("c20126",this,other.c20126),
   c20200("c20200",this,other.c20200),
   c20201("c20201",this,other.c20201),
   c20202("c20202",this,other.c20202),
   c20204("c20204",this,other.c20204),
   c20206("c20206",this,other.c20206),
   c20210("c20210",this,other.c20210),
   c20211("c20211",this,other.c20211),
   c20212("c20212",this,other.c20212),
   c20214("c20214",this,other.c20214),
   c20216("c20216",this,other.c20216),
   c20220("c20220",this,other.c20220),
   c20221("c20221",this,other.c20221),
   c20222("c20222",this,other.c20222),
   c20224("c20224",this,other.c20224),
   c20226("c20226",this,other.c20226),
   c21000("c21000",this,other.c21000),
   c21001("c21001",this,other.c21001),
   c21002("c21002",this,other.c21002),
   c21004("c21004",this,other.c21004),
   c21006("c21006",this,other.c21006),
   c21010("c21010",this,other.c21010),
   c21011("c21011",this,other.c21011),
   c21012("c21012",this,other.c21012),
   c21014("c21014",this,other.c21014),
   c21016("c21016",this,other.c21016),
   c21020("c21020",this,other.c21020),
   c21021("c21021",this,other.c21021),
   c21022("c21022",this,other.c21022),
   c21024("c21024",this,other.c21024),
   c21026("c21026",this,other.c21026),
   c21100("c21100",this,other.c21100),
   c21101("c21101",this,other.c21101),
   c21102("c21102",this,other.c21102),
   c21104("c21104",this,other.c21104),
   c21106("c21106",this,other.c21106),
   c21110("c21110",this,other.c21110),
   c21111("c21111",this,other.c21111),
   c21112("c21112",this,other.c21112),
   c21114("c21114",this,other.c21114),
   c21116("c21116",this,other.c21116),
   c21120("c21120",this,other.c21120),
   c21121("c21121",this,other.c21121),
   c21122("c21122",this,other.c21122),
   c21124("c21124",this,other.c21124),
   c21126("c21126",this,other.c21126),
   c21200("c21200",this,other.c21200),
   c21201("c21201",this,other.c21201),
   c21202("c21202",this,other.c21202),
   c21204("c21204",this,other.c21204),
   c21206("c21206",this,other.c21206),
   c21210("c21210",this,other.c21210),
   c21211("c21211",this,other.c21211),
   c21212("c21212",this,other.c21212),
   c21214("c21214",this,other.c21214),
   c21216("c21216",this,other.c21216),
   c21220("c21220",this,other.c21220),
   c21221("c21221",this,other.c21221),
   c21222("c21222",this,other.c21222),
   c21224("c21224",this,other.c21224),
   c22000("c22000",this,other.c22000),
   c22001("c22001",this,other.c22001),
   c22002("c22002",this,other.c22002),
   c22004("c22004",this,other.c22004),
   c22006("c22006",this,other.c22006),
   c22010("c22010",this,other.c22010),
   c22011("c22011",this,other.c22011),
   c22012("c22012",this,other.c22012),
   c22014("c22014",this,other.c22014),
   c22016("c22016",this,other.c22016),
   c22020("c22020",this,other.c22020),
   c22021("c22021",this,other.c22021),
   c22022("c22022",this,other.c22022),
   c22024("c22024",this,other.c22024),
   c22026("c22026",this,other.c22026),
   c22100("c22100",this,other.c22100),
   c22101("c22101",this,other.c22101),
   c22102("c22102",this,other.c22102),
   c22104("c22104",this,other.c22104),
   c22106("c22106",this,other.c22106),
   c22110("c22110",this,other.c22110),
   c22111("c22111",this,other.c22111),
   c22112("c22112",this,other.c22112),
   c22114("c22114",this,other.c22114),
   c22116("c22116",this,other.c22116),
   c22120("c22120",this,other.c22120),
   c22121("c22121",this,other.c22121),
   c22122("c22122",this,other.c22122),
   c22124("c22124",this,other.c22124),
   c22200("c22200",this,other.c22200),
   c22201("c22201",this,other.c22201),
   c22202("c22202",this,other.c22202),
   c22204("c22204",this,other.c22204),
   c22206("c22206",this,other.c22206),
   c22210("c22210",this,other.c22210),
   c22211("c22211",this,other.c22211),
   c22212("c22212",this,other.c22212),
   c22214("c22214",this,other.c22214),
   c22220("c22220",this,other.c22220),
   c22221("c22221",this,other.c22221),
   c22222("c22222",this,other.c22222),
   c22224("c22224",this,other.c22224)
 { 
 } 



 Double_t RooLegendre5Pdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 





double coeff5[4][4][4][4][7];
coeff5[0][0][0][0][0] = c00000;
coeff5[0][0][0][0][1] = c00001;
coeff5[0][0][0][0][2] = c00002;
coeff5[0][0][0][0][4] = c00004;
coeff5[0][0][0][0][6] = c00006;
coeff5[0][0][0][1][0] = c00010;
coeff5[0][0][0][1][1] = c00011;
coeff5[0][0][0][1][2] = c00012;
coeff5[0][0][0][1][4] = c00014;
coeff5[0][0][0][1][6] = c00016;
coeff5[0][0][0][2][0] = c00020;
coeff5[0][0][0][2][1] = c00021;
coeff5[0][0][0][2][2] = c00022;
coeff5[0][0][0][2][4] = c00024;
coeff5[0][0][0][2][6] = c00026;
coeff5[0][0][1][0][0] = c00100;
coeff5[0][0][1][0][1] = c00101;
coeff5[0][0][1][0][2] = c00102;
coeff5[0][0][1][0][4] = c00104;
coeff5[0][0][1][0][6] = c00106;
coeff5[0][0][1][1][0] = c00110;
coeff5[0][0][1][1][1] = c00111;
coeff5[0][0][1][1][2] = c00112;
coeff5[0][0][1][1][4] = c00114;
coeff5[0][0][1][1][6] = c00116;
coeff5[0][0][1][2][0] = c00120;
coeff5[0][0][1][2][1] = c00121;
coeff5[0][0][1][2][2] = c00122;
coeff5[0][0][1][2][4] = c00124;
coeff5[0][0][1][2][6] = c00126;
coeff5[0][0][2][0][0] = c00200;
coeff5[0][0][2][0][1] = c00201;
coeff5[0][0][2][0][2] = c00202;
coeff5[0][0][2][0][4] = c00204;
coeff5[0][0][2][0][6] = c00206;
coeff5[0][0][2][1][0] = c00210;
coeff5[0][0][2][1][1] = c00211;
coeff5[0][0][2][1][2] = c00212;
coeff5[0][0][2][1][4] = c00214;
coeff5[0][0][2][1][6] = c00216;
coeff5[0][0][2][2][0] = c00220;
coeff5[0][0][2][2][1] = c00221;
coeff5[0][0][2][2][2] = c00222;
coeff5[0][0][2][2][4] = c00224;
coeff5[0][0][2][2][6] = c00226;
coeff5[0][1][0][0][0] = c01000;
coeff5[0][1][0][0][1] = c01001;
coeff5[0][1][0][0][2] = c01002;
coeff5[0][1][0][0][4] = c01004;
coeff5[0][1][0][0][6] = c01006;
coeff5[0][1][0][1][0] = c01010;
coeff5[0][1][0][1][1] = c01011;
coeff5[0][1][0][1][2] = c01012;
coeff5[0][1][0][1][4] = c01014;
coeff5[0][1][0][1][6] = c01016;
coeff5[0][1][0][2][0] = c01020;
coeff5[0][1][0][2][1] = c01021;
coeff5[0][1][0][2][2] = c01022;
coeff5[0][1][0][2][4] = c01024;
coeff5[0][1][0][2][6] = c01026;
coeff5[0][1][1][0][0] = c01100;
coeff5[0][1][1][0][1] = c01101;
coeff5[0][1][1][0][2] = c01102;
coeff5[0][1][1][0][4] = c01104;
coeff5[0][1][1][0][6] = c01106;
coeff5[0][1][1][1][0] = c01110;
coeff5[0][1][1][1][1] = c01111;
coeff5[0][1][1][1][2] = c01112;
coeff5[0][1][1][1][4] = c01114;
coeff5[0][1][1][1][6] = c01116;
coeff5[0][1][1][2][0] = c01120;
coeff5[0][1][1][2][1] = c01121;
coeff5[0][1][1][2][2] = c01122;
coeff5[0][1][1][2][4] = c01124;
coeff5[0][1][1][2][6] = c01126;
coeff5[0][1][2][0][0] = c01200;
coeff5[0][1][2][0][1] = c01201;
coeff5[0][1][2][0][2] = c01202;
coeff5[0][1][2][0][4] = c01204;
coeff5[0][1][2][0][6] = c01206;
coeff5[0][1][2][1][0] = c01210;
coeff5[0][1][2][1][1] = c01211;
coeff5[0][1][2][1][2] = c01212;
coeff5[0][1][2][1][4] = c01214;
coeff5[0][1][2][1][6] = c01216;
coeff5[0][1][2][2][0] = c01220;
coeff5[0][1][2][2][1] = c01221;
coeff5[0][1][2][2][2] = c01222;
coeff5[0][1][2][2][4] = c01224;
coeff5[0][1][2][2][6] = c01226;
coeff5[0][2][0][0][0] = c02000;
coeff5[0][2][0][0][1] = c02001;
coeff5[0][2][0][0][2] = c02002;
coeff5[0][2][0][0][4] = c02004;
coeff5[0][2][0][0][6] = c02006;
coeff5[0][2][0][1][0] = c02010;
coeff5[0][2][0][1][1] = c02011;
coeff5[0][2][0][1][2] = c02012;
coeff5[0][2][0][1][4] = c02014;
coeff5[0][2][0][1][6] = c02016;
coeff5[0][2][0][2][0] = c02020;
coeff5[0][2][0][2][1] = c02021;
coeff5[0][2][0][2][2] = c02022;
coeff5[0][2][0][2][4] = c02024;
coeff5[0][2][0][2][6] = c02026;
coeff5[0][2][1][0][0] = c02100;
coeff5[0][2][1][0][1] = c02101;
coeff5[0][2][1][0][2] = c02102;
coeff5[0][2][1][0][4] = c02104;
coeff5[0][2][1][0][6] = c02106;
coeff5[0][2][1][1][0] = c02110;
coeff5[0][2][1][1][1] = c02111;
coeff5[0][2][1][1][2] = c02112;
coeff5[0][2][1][1][4] = c02114;
coeff5[0][2][1][1][6] = c02116;
coeff5[0][2][1][2][0] = c02120;
coeff5[0][2][1][2][1] = c02121;
coeff5[0][2][1][2][2] = c02122;
coeff5[0][2][1][2][4] = c02124;
coeff5[0][2][1][2][6] = c02126;
coeff5[0][2][2][0][0] = c02200;
coeff5[0][2][2][0][1] = c02201;
coeff5[0][2][2][0][2] = c02202;
coeff5[0][2][2][0][4] = c02204;
coeff5[0][2][2][0][6] = c02206;
coeff5[0][2][2][1][0] = c02210;
coeff5[0][2][2][1][1] = c02211;
coeff5[0][2][2][1][2] = c02212;
coeff5[0][2][2][1][4] = c02214;
coeff5[0][2][2][1][6] = c02216;
coeff5[0][2][2][2][0] = c02220;
coeff5[0][2][2][2][1] = c02221;
coeff5[0][2][2][2][2] = c02222;
coeff5[0][2][2][2][4] = c02224;
coeff5[0][2][2][2][6] = c02226;
coeff5[1][0][0][0][0] = c10000;
coeff5[1][0][0][0][1] = c10001;
coeff5[1][0][0][0][2] = c10002;
coeff5[1][0][0][0][4] = c10004;
coeff5[1][0][0][0][6] = c10006;
coeff5[1][0][0][1][0] = c10010;
coeff5[1][0][0][1][1] = c10011;
coeff5[1][0][0][1][2] = c10012;
coeff5[1][0][0][1][4] = c10014;
coeff5[1][0][0][1][6] = c10016;
coeff5[1][0][0][2][0] = c10020;
coeff5[1][0][0][2][1] = c10021;
coeff5[1][0][0][2][2] = c10022;
coeff5[1][0][0][2][4] = c10024;
coeff5[1][0][0][2][6] = c10026;
coeff5[1][0][1][0][0] = c10100;
coeff5[1][0][1][0][1] = c10101;
coeff5[1][0][1][0][2] = c10102;
coeff5[1][0][1][0][4] = c10104;
coeff5[1][0][1][0][6] = c10106;
coeff5[1][0][1][1][0] = c10110;
coeff5[1][0][1][1][1] = c10111;
coeff5[1][0][1][1][2] = c10112;
coeff5[1][0][1][1][4] = c10114;
coeff5[1][0][1][1][6] = c10116;
coeff5[1][0][1][2][0] = c10120;
coeff5[1][0][1][2][1] = c10121;
coeff5[1][0][1][2][2] = c10122;
coeff5[1][0][1][2][4] = c10124;
coeff5[1][0][1][2][6] = c10126;
coeff5[1][0][2][0][0] = c10200;
coeff5[1][0][2][0][1] = c10201;
coeff5[1][0][2][0][2] = c10202;
coeff5[1][0][2][0][4] = c10204;
coeff5[1][0][2][0][6] = c10206;
coeff5[1][0][2][1][0] = c10210;
coeff5[1][0][2][1][1] = c10211;
coeff5[1][0][2][1][2] = c10212;
coeff5[1][0][2][1][4] = c10214;
coeff5[1][0][2][1][6] = c10216;
coeff5[1][0][2][2][0] = c10220;
coeff5[1][0][2][2][1] = c10221;
coeff5[1][0][2][2][2] = c10222;
coeff5[1][0][2][2][4] = c10224;
coeff5[1][0][2][2][6] = c10226;
coeff5[1][1][0][0][0] = c11000;
coeff5[1][1][0][0][1] = c11001;
coeff5[1][1][0][0][2] = c11002;
coeff5[1][1][0][0][4] = c11004;
coeff5[1][1][0][0][6] = c11006;
coeff5[1][1][0][1][0] = c11010;
coeff5[1][1][0][1][1] = c11011;
coeff5[1][1][0][1][2] = c11012;
coeff5[1][1][0][1][4] = c11014;
coeff5[1][1][0][1][6] = c11016;
coeff5[1][1][0][2][0] = c11020;
coeff5[1][1][0][2][1] = c11021;
coeff5[1][1][0][2][2] = c11022;
coeff5[1][1][0][2][4] = c11024;
coeff5[1][1][0][2][6] = c11026;
coeff5[1][1][1][0][0] = c11100;
coeff5[1][1][1][0][1] = c11101;
coeff5[1][1][1][0][2] = c11102;
coeff5[1][1][1][0][4] = c11104;
coeff5[1][1][1][0][6] = c11106;
coeff5[1][1][1][1][0] = c11110;
coeff5[1][1][1][1][1] = c11111;
coeff5[1][1][1][1][2] = c11112;
coeff5[1][1][1][1][4] = c11114;
coeff5[1][1][1][1][6] = c11116;
coeff5[1][1][1][2][0] = c11120;
coeff5[1][1][1][2][1] = c11121;
coeff5[1][1][1][2][2] = c11122;
coeff5[1][1][1][2][4] = c11124;
coeff5[1][1][1][2][6] = c11126;
coeff5[1][1][2][0][0] = c11200;
coeff5[1][1][2][0][1] = c11201;
coeff5[1][1][2][0][2] = c11202;
coeff5[1][1][2][0][4] = c11204;
coeff5[1][1][2][0][6] = c11206;
coeff5[1][1][2][1][0] = c11210;
coeff5[1][1][2][1][1] = c11211;
coeff5[1][1][2][1][2] = c11212;
coeff5[1][1][2][1][4] = c11214;
coeff5[1][1][2][1][6] = c11216;
coeff5[1][1][2][2][0] = c11220;
coeff5[1][1][2][2][1] = c11221;
coeff5[1][1][2][2][2] = c11222;
coeff5[1][1][2][2][4] = c11224;
coeff5[1][1][2][2][6] = c11226;
coeff5[1][2][0][0][0] = c12000;
coeff5[1][2][0][0][1] = c12001;
coeff5[1][2][0][0][2] = c12002;
coeff5[1][2][0][0][4] = c12004;
coeff5[1][2][0][0][6] = c12006;
coeff5[1][2][0][1][0] = c12010;
coeff5[1][2][0][1][1] = c12011;
coeff5[1][2][0][1][2] = c12012;
coeff5[1][2][0][1][4] = c12014;
coeff5[1][2][0][1][6] = c12016;
coeff5[1][2][0][2][0] = c12020;
coeff5[1][2][0][2][1] = c12021;
coeff5[1][2][0][2][2] = c12022;
coeff5[1][2][0][2][4] = c12024;
coeff5[1][2][0][2][6] = c12026;
coeff5[1][2][1][0][0] = c12100;
coeff5[1][2][1][0][1] = c12101;
coeff5[1][2][1][0][2] = c12102;
coeff5[1][2][1][0][4] = c12104;
coeff5[1][2][1][0][6] = c12106;
coeff5[1][2][1][1][0] = c12110;
coeff5[1][2][1][1][1] = c12111;
coeff5[1][2][1][1][2] = c12112;
coeff5[1][2][1][1][4] = c12114;
coeff5[1][2][1][1][6] = c12116;
coeff5[1][2][1][2][0] = c12120;
coeff5[1][2][1][2][1] = c12121;
coeff5[1][2][1][2][2] = c12122;
coeff5[1][2][1][2][4] = c12124;
coeff5[1][2][1][2][6] = c12126;
coeff5[1][2][2][0][0] = c12200;
coeff5[1][2][2][0][1] = c12201;
coeff5[1][2][2][0][2] = c12202;
coeff5[1][2][2][0][4] = c12204;
coeff5[1][2][2][0][6] = c12206;
coeff5[1][2][2][1][0] = c12210;
coeff5[1][2][2][1][1] = c12211;
coeff5[1][2][2][1][2] = c12212;
coeff5[1][2][2][1][4] = c12214;
coeff5[1][2][2][1][6] = c12216;
coeff5[1][2][2][2][0] = c12220;
coeff5[1][2][2][2][1] = c12221;
coeff5[1][2][2][2][2] = c12222;
coeff5[1][2][2][2][4] = c12224;
coeff5[2][0][0][0][0] = c20000;
coeff5[2][0][0][0][1] = c20001;
coeff5[2][0][0][0][2] = c20002;
coeff5[2][0][0][0][4] = c20004;
coeff5[2][0][0][0][6] = c20006;
coeff5[2][0][0][1][0] = c20010;
coeff5[2][0][0][1][1] = c20011;
coeff5[2][0][0][1][2] = c20012;
coeff5[2][0][0][1][4] = c20014;
coeff5[2][0][0][1][6] = c20016;
coeff5[2][0][0][2][0] = c20020;
coeff5[2][0][0][2][1] = c20021;
coeff5[2][0][0][2][2] = c20022;
coeff5[2][0][0][2][4] = c20024;
coeff5[2][0][0][2][6] = c20026;
coeff5[2][0][1][0][0] = c20100;
coeff5[2][0][1][0][1] = c20101;
coeff5[2][0][1][0][2] = c20102;
coeff5[2][0][1][0][4] = c20104;
coeff5[2][0][1][0][6] = c20106;
coeff5[2][0][1][1][0] = c20110;
coeff5[2][0][1][1][1] = c20111;
coeff5[2][0][1][1][2] = c20112;
coeff5[2][0][1][1][4] = c20114;
coeff5[2][0][1][1][6] = c20116;
coeff5[2][0][1][2][0] = c20120;
coeff5[2][0][1][2][1] = c20121;
coeff5[2][0][1][2][2] = c20122;
coeff5[2][0][1][2][4] = c20124;
coeff5[2][0][1][2][6] = c20126;
coeff5[2][0][2][0][0] = c20200;
coeff5[2][0][2][0][1] = c20201;
coeff5[2][0][2][0][2] = c20202;
coeff5[2][0][2][0][4] = c20204;
coeff5[2][0][2][0][6] = c20206;
coeff5[2][0][2][1][0] = c20210;
coeff5[2][0][2][1][1] = c20211;
coeff5[2][0][2][1][2] = c20212;
coeff5[2][0][2][1][4] = c20214;
coeff5[2][0][2][1][6] = c20216;
coeff5[2][0][2][2][0] = c20220;
coeff5[2][0][2][2][1] = c20221;
coeff5[2][0][2][2][2] = c20222;
coeff5[2][0][2][2][4] = c20224;
coeff5[2][0][2][2][6] = c20226;
coeff5[2][1][0][0][0] = c21000;
coeff5[2][1][0][0][1] = c21001;
coeff5[2][1][0][0][2] = c21002;
coeff5[2][1][0][0][4] = c21004;
coeff5[2][1][0][0][6] = c21006;
coeff5[2][1][0][1][0] = c21010;
coeff5[2][1][0][1][1] = c21011;
coeff5[2][1][0][1][2] = c21012;
coeff5[2][1][0][1][4] = c21014;
coeff5[2][1][0][1][6] = c21016;
coeff5[2][1][0][2][0] = c21020;
coeff5[2][1][0][2][1] = c21021;
coeff5[2][1][0][2][2] = c21022;
coeff5[2][1][0][2][4] = c21024;
coeff5[2][1][0][2][6] = c21026;
coeff5[2][1][1][0][0] = c21100;
coeff5[2][1][1][0][1] = c21101;
coeff5[2][1][1][0][2] = c21102;
coeff5[2][1][1][0][4] = c21104;
coeff5[2][1][1][0][6] = c21106;
coeff5[2][1][1][1][0] = c21110;
coeff5[2][1][1][1][1] = c21111;
coeff5[2][1][1][1][2] = c21112;
coeff5[2][1][1][1][4] = c21114;
coeff5[2][1][1][1][6] = c21116;
coeff5[2][1][1][2][0] = c21120;
coeff5[2][1][1][2][1] = c21121;
coeff5[2][1][1][2][2] = c21122;
coeff5[2][1][1][2][4] = c21124;
coeff5[2][1][1][2][6] = c21126;
coeff5[2][1][2][0][0] = c21200;
coeff5[2][1][2][0][1] = c21201;
coeff5[2][1][2][0][2] = c21202;
coeff5[2][1][2][0][4] = c21204;
coeff5[2][1][2][0][6] = c21206;
coeff5[2][1][2][1][0] = c21210;
coeff5[2][1][2][1][1] = c21211;
coeff5[2][1][2][1][2] = c21212;
coeff5[2][1][2][1][4] = c21214;
coeff5[2][1][2][1][6] = c21216;
coeff5[2][1][2][2][0] = c21220;
coeff5[2][1][2][2][1] = c21221;
coeff5[2][1][2][2][2] = c21222;
coeff5[2][1][2][2][4] = c21224;
coeff5[2][2][0][0][0] = c22000;
coeff5[2][2][0][0][1] = c22001;
coeff5[2][2][0][0][2] = c22002;
coeff5[2][2][0][0][4] = c22004;
coeff5[2][2][0][0][6] = c22006;
coeff5[2][2][0][1][0] = c22010;
coeff5[2][2][0][1][1] = c22011;
coeff5[2][2][0][1][2] = c22012;
coeff5[2][2][0][1][4] = c22014;
coeff5[2][2][0][1][6] = c22016;
coeff5[2][2][0][2][0] = c22020;
coeff5[2][2][0][2][1] = c22021;
coeff5[2][2][0][2][2] = c22022;
coeff5[2][2][0][2][4] = c22024;
coeff5[2][2][0][2][6] = c22026;
coeff5[2][2][1][0][0] = c22100;
coeff5[2][2][1][0][1] = c22101;
coeff5[2][2][1][0][2] = c22102;
coeff5[2][2][1][0][4] = c22104;
coeff5[2][2][1][0][6] = c22106;
coeff5[2][2][1][1][0] = c22110;
coeff5[2][2][1][1][1] = c22111;
coeff5[2][2][1][1][2] = c22112;
coeff5[2][2][1][1][4] = c22114;
coeff5[2][2][1][1][6] = c22116;
coeff5[2][2][1][2][0] = c22120;
coeff5[2][2][1][2][1] = c22121;
coeff5[2][2][1][2][2] = c22122;
coeff5[2][2][1][2][4] = c22124;
coeff5[2][2][2][0][0] = c22200;
coeff5[2][2][2][0][1] = c22201;
coeff5[2][2][2][0][2] = c22202;
coeff5[2][2][2][0][4] = c22204;
coeff5[2][2][2][0][6] = c22206;
coeff5[2][2][2][1][0] = c22210;
coeff5[2][2][2][1][1] = c22211;
coeff5[2][2][2][1][2] = c22212;
coeff5[2][2][2][1][4] = c22214;
coeff5[2][2][2][2][0] = c22220;
coeff5[2][2][2][2][1] = c22221;
coeff5[2][2][2][2][2] = c22222;
coeff5[2][2][2][2][4] = c22224;





   return pdfval5f5(costheta0,costheta1,costheta2,phi1,phi2,coeff5); 
 } 



 Int_t RooLegendre5Pdf::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* /*rangeName*/) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   // if (matchArgs(allVars,analVars,x)) return 1 ; 

   //5
   if ( matchArgs(allVars,analVars, RooArgSet(costheta0.arg(),costheta1.arg(),costheta2.arg(),phi1.arg(),phi2.arg()) ) ) return 1;

   // //4
   if ( matchArgs(allVars,analVars, RooArgSet(costheta1.arg(),costheta2.arg(),phi1.arg(),phi2.arg()) ) ) return 2;
   if ( matchArgs(allVars,analVars, RooArgSet(costheta0.arg(),costheta2.arg(),phi1.arg(),phi2.arg()) ) ) return 3;
   if ( matchArgs(allVars,analVars, RooArgSet(costheta0.arg(),costheta1.arg(),phi1.arg(),phi2.arg()) ) ) return 4;
   if ( matchArgs(allVars,analVars, RooArgSet(costheta0.arg(),costheta1.arg(),costheta2.arg(),phi2.arg()) ) ) return 5;
   if ( matchArgs(allVars,analVars, RooArgSet(costheta0.arg(),costheta1.arg(),costheta2.arg(),phi1.arg()) ) ) return 6;

   return 0 ; 
 } 



 Double_t RooLegendre5Pdf::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   // assert(code==1) ; 
   // return (x.max(rangeName)-x.min(rangeName)) ; 



double coeff5[4][4][4][4][7];
coeff5[0][0][0][0][0] = c00000;
coeff5[0][0][0][0][1] = c00001;
coeff5[0][0][0][0][2] = c00002;
coeff5[0][0][0][0][4] = c00004;
coeff5[0][0][0][0][6] = c00006;
coeff5[0][0][0][1][0] = c00010;
coeff5[0][0][0][1][1] = c00011;
coeff5[0][0][0][1][2] = c00012;
coeff5[0][0][0][1][4] = c00014;
coeff5[0][0][0][1][6] = c00016;
coeff5[0][0][0][2][0] = c00020;
coeff5[0][0][0][2][1] = c00021;
coeff5[0][0][0][2][2] = c00022;
coeff5[0][0][0][2][4] = c00024;
coeff5[0][0][0][2][6] = c00026;
coeff5[0][0][1][0][0] = c00100;
coeff5[0][0][1][0][1] = c00101;
coeff5[0][0][1][0][2] = c00102;
coeff5[0][0][1][0][4] = c00104;
coeff5[0][0][1][0][6] = c00106;
coeff5[0][0][1][1][0] = c00110;
coeff5[0][0][1][1][1] = c00111;
coeff5[0][0][1][1][2] = c00112;
coeff5[0][0][1][1][4] = c00114;
coeff5[0][0][1][1][6] = c00116;
coeff5[0][0][1][2][0] = c00120;
coeff5[0][0][1][2][1] = c00121;
coeff5[0][0][1][2][2] = c00122;
coeff5[0][0][1][2][4] = c00124;
coeff5[0][0][1][2][6] = c00126;
coeff5[0][0][2][0][0] = c00200;
coeff5[0][0][2][0][1] = c00201;
coeff5[0][0][2][0][2] = c00202;
coeff5[0][0][2][0][4] = c00204;
coeff5[0][0][2][0][6] = c00206;
coeff5[0][0][2][1][0] = c00210;
coeff5[0][0][2][1][1] = c00211;
coeff5[0][0][2][1][2] = c00212;
coeff5[0][0][2][1][4] = c00214;
coeff5[0][0][2][1][6] = c00216;
coeff5[0][0][2][2][0] = c00220;
coeff5[0][0][2][2][1] = c00221;
coeff5[0][0][2][2][2] = c00222;
coeff5[0][0][2][2][4] = c00224;
coeff5[0][0][2][2][6] = c00226;
coeff5[0][1][0][0][0] = c01000;
coeff5[0][1][0][0][1] = c01001;
coeff5[0][1][0][0][2] = c01002;
coeff5[0][1][0][0][4] = c01004;
coeff5[0][1][0][0][6] = c01006;
coeff5[0][1][0][1][0] = c01010;
coeff5[0][1][0][1][1] = c01011;
coeff5[0][1][0][1][2] = c01012;
coeff5[0][1][0][1][4] = c01014;
coeff5[0][1][0][1][6] = c01016;
coeff5[0][1][0][2][0] = c01020;
coeff5[0][1][0][2][1] = c01021;
coeff5[0][1][0][2][2] = c01022;
coeff5[0][1][0][2][4] = c01024;
coeff5[0][1][0][2][6] = c01026;
coeff5[0][1][1][0][0] = c01100;
coeff5[0][1][1][0][1] = c01101;
coeff5[0][1][1][0][2] = c01102;
coeff5[0][1][1][0][4] = c01104;
coeff5[0][1][1][0][6] = c01106;
coeff5[0][1][1][1][0] = c01110;
coeff5[0][1][1][1][1] = c01111;
coeff5[0][1][1][1][2] = c01112;
coeff5[0][1][1][1][4] = c01114;
coeff5[0][1][1][1][6] = c01116;
coeff5[0][1][1][2][0] = c01120;
coeff5[0][1][1][2][1] = c01121;
coeff5[0][1][1][2][2] = c01122;
coeff5[0][1][1][2][4] = c01124;
coeff5[0][1][1][2][6] = c01126;
coeff5[0][1][2][0][0] = c01200;
coeff5[0][1][2][0][1] = c01201;
coeff5[0][1][2][0][2] = c01202;
coeff5[0][1][2][0][4] = c01204;
coeff5[0][1][2][0][6] = c01206;
coeff5[0][1][2][1][0] = c01210;
coeff5[0][1][2][1][1] = c01211;
coeff5[0][1][2][1][2] = c01212;
coeff5[0][1][2][1][4] = c01214;
coeff5[0][1][2][1][6] = c01216;
coeff5[0][1][2][2][0] = c01220;
coeff5[0][1][2][2][1] = c01221;
coeff5[0][1][2][2][2] = c01222;
coeff5[0][1][2][2][4] = c01224;
coeff5[0][1][2][2][6] = c01226;
coeff5[0][2][0][0][0] = c02000;
coeff5[0][2][0][0][1] = c02001;
coeff5[0][2][0][0][2] = c02002;
coeff5[0][2][0][0][4] = c02004;
coeff5[0][2][0][0][6] = c02006;
coeff5[0][2][0][1][0] = c02010;
coeff5[0][2][0][1][1] = c02011;
coeff5[0][2][0][1][2] = c02012;
coeff5[0][2][0][1][4] = c02014;
coeff5[0][2][0][1][6] = c02016;
coeff5[0][2][0][2][0] = c02020;
coeff5[0][2][0][2][1] = c02021;
coeff5[0][2][0][2][2] = c02022;
coeff5[0][2][0][2][4] = c02024;
coeff5[0][2][0][2][6] = c02026;
coeff5[0][2][1][0][0] = c02100;
coeff5[0][2][1][0][1] = c02101;
coeff5[0][2][1][0][2] = c02102;
coeff5[0][2][1][0][4] = c02104;
coeff5[0][2][1][0][6] = c02106;
coeff5[0][2][1][1][0] = c02110;
coeff5[0][2][1][1][1] = c02111;
coeff5[0][2][1][1][2] = c02112;
coeff5[0][2][1][1][4] = c02114;
coeff5[0][2][1][1][6] = c02116;
coeff5[0][2][1][2][0] = c02120;
coeff5[0][2][1][2][1] = c02121;
coeff5[0][2][1][2][2] = c02122;
coeff5[0][2][1][2][4] = c02124;
coeff5[0][2][1][2][6] = c02126;
coeff5[0][2][2][0][0] = c02200;
coeff5[0][2][2][0][1] = c02201;
coeff5[0][2][2][0][2] = c02202;
coeff5[0][2][2][0][4] = c02204;
coeff5[0][2][2][0][6] = c02206;
coeff5[0][2][2][1][0] = c02210;
coeff5[0][2][2][1][1] = c02211;
coeff5[0][2][2][1][2] = c02212;
coeff5[0][2][2][1][4] = c02214;
coeff5[0][2][2][1][6] = c02216;
coeff5[0][2][2][2][0] = c02220;
coeff5[0][2][2][2][1] = c02221;
coeff5[0][2][2][2][2] = c02222;
coeff5[0][2][2][2][4] = c02224;
coeff5[0][2][2][2][6] = c02226;
coeff5[1][0][0][0][0] = c10000;
coeff5[1][0][0][0][1] = c10001;
coeff5[1][0][0][0][2] = c10002;
coeff5[1][0][0][0][4] = c10004;
coeff5[1][0][0][0][6] = c10006;
coeff5[1][0][0][1][0] = c10010;
coeff5[1][0][0][1][1] = c10011;
coeff5[1][0][0][1][2] = c10012;
coeff5[1][0][0][1][4] = c10014;
coeff5[1][0][0][1][6] = c10016;
coeff5[1][0][0][2][0] = c10020;
coeff5[1][0][0][2][1] = c10021;
coeff5[1][0][0][2][2] = c10022;
coeff5[1][0][0][2][4] = c10024;
coeff5[1][0][0][2][6] = c10026;
coeff5[1][0][1][0][0] = c10100;
coeff5[1][0][1][0][1] = c10101;
coeff5[1][0][1][0][2] = c10102;
coeff5[1][0][1][0][4] = c10104;
coeff5[1][0][1][0][6] = c10106;
coeff5[1][0][1][1][0] = c10110;
coeff5[1][0][1][1][1] = c10111;
coeff5[1][0][1][1][2] = c10112;
coeff5[1][0][1][1][4] = c10114;
coeff5[1][0][1][1][6] = c10116;
coeff5[1][0][1][2][0] = c10120;
coeff5[1][0][1][2][1] = c10121;
coeff5[1][0][1][2][2] = c10122;
coeff5[1][0][1][2][4] = c10124;
coeff5[1][0][1][2][6] = c10126;
coeff5[1][0][2][0][0] = c10200;
coeff5[1][0][2][0][1] = c10201;
coeff5[1][0][2][0][2] = c10202;
coeff5[1][0][2][0][4] = c10204;
coeff5[1][0][2][0][6] = c10206;
coeff5[1][0][2][1][0] = c10210;
coeff5[1][0][2][1][1] = c10211;
coeff5[1][0][2][1][2] = c10212;
coeff5[1][0][2][1][4] = c10214;
coeff5[1][0][2][1][6] = c10216;
coeff5[1][0][2][2][0] = c10220;
coeff5[1][0][2][2][1] = c10221;
coeff5[1][0][2][2][2] = c10222;
coeff5[1][0][2][2][4] = c10224;
coeff5[1][0][2][2][6] = c10226;
coeff5[1][1][0][0][0] = c11000;
coeff5[1][1][0][0][1] = c11001;
coeff5[1][1][0][0][2] = c11002;
coeff5[1][1][0][0][4] = c11004;
coeff5[1][1][0][0][6] = c11006;
coeff5[1][1][0][1][0] = c11010;
coeff5[1][1][0][1][1] = c11011;
coeff5[1][1][0][1][2] = c11012;
coeff5[1][1][0][1][4] = c11014;
coeff5[1][1][0][1][6] = c11016;
coeff5[1][1][0][2][0] = c11020;
coeff5[1][1][0][2][1] = c11021;
coeff5[1][1][0][2][2] = c11022;
coeff5[1][1][0][2][4] = c11024;
coeff5[1][1][0][2][6] = c11026;
coeff5[1][1][1][0][0] = c11100;
coeff5[1][1][1][0][1] = c11101;
coeff5[1][1][1][0][2] = c11102;
coeff5[1][1][1][0][4] = c11104;
coeff5[1][1][1][0][6] = c11106;
coeff5[1][1][1][1][0] = c11110;
coeff5[1][1][1][1][1] = c11111;
coeff5[1][1][1][1][2] = c11112;
coeff5[1][1][1][1][4] = c11114;
coeff5[1][1][1][1][6] = c11116;
coeff5[1][1][1][2][0] = c11120;
coeff5[1][1][1][2][1] = c11121;
coeff5[1][1][1][2][2] = c11122;
coeff5[1][1][1][2][4] = c11124;
coeff5[1][1][1][2][6] = c11126;
coeff5[1][1][2][0][0] = c11200;
coeff5[1][1][2][0][1] = c11201;
coeff5[1][1][2][0][2] = c11202;
coeff5[1][1][2][0][4] = c11204;
coeff5[1][1][2][0][6] = c11206;
coeff5[1][1][2][1][0] = c11210;
coeff5[1][1][2][1][1] = c11211;
coeff5[1][1][2][1][2] = c11212;
coeff5[1][1][2][1][4] = c11214;
coeff5[1][1][2][1][6] = c11216;
coeff5[1][1][2][2][0] = c11220;
coeff5[1][1][2][2][1] = c11221;
coeff5[1][1][2][2][2] = c11222;
coeff5[1][1][2][2][4] = c11224;
coeff5[1][1][2][2][6] = c11226;
coeff5[1][2][0][0][0] = c12000;
coeff5[1][2][0][0][1] = c12001;
coeff5[1][2][0][0][2] = c12002;
coeff5[1][2][0][0][4] = c12004;
coeff5[1][2][0][0][6] = c12006;
coeff5[1][2][0][1][0] = c12010;
coeff5[1][2][0][1][1] = c12011;
coeff5[1][2][0][1][2] = c12012;
coeff5[1][2][0][1][4] = c12014;
coeff5[1][2][0][1][6] = c12016;
coeff5[1][2][0][2][0] = c12020;
coeff5[1][2][0][2][1] = c12021;
coeff5[1][2][0][2][2] = c12022;
coeff5[1][2][0][2][4] = c12024;
coeff5[1][2][0][2][6] = c12026;
coeff5[1][2][1][0][0] = c12100;
coeff5[1][2][1][0][1] = c12101;
coeff5[1][2][1][0][2] = c12102;
coeff5[1][2][1][0][4] = c12104;
coeff5[1][2][1][0][6] = c12106;
coeff5[1][2][1][1][0] = c12110;
coeff5[1][2][1][1][1] = c12111;
coeff5[1][2][1][1][2] = c12112;
coeff5[1][2][1][1][4] = c12114;
coeff5[1][2][1][1][6] = c12116;
coeff5[1][2][1][2][0] = c12120;
coeff5[1][2][1][2][1] = c12121;
coeff5[1][2][1][2][2] = c12122;
coeff5[1][2][1][2][4] = c12124;
coeff5[1][2][1][2][6] = c12126;
coeff5[1][2][2][0][0] = c12200;
coeff5[1][2][2][0][1] = c12201;
coeff5[1][2][2][0][2] = c12202;
coeff5[1][2][2][0][4] = c12204;
coeff5[1][2][2][0][6] = c12206;
coeff5[1][2][2][1][0] = c12210;
coeff5[1][2][2][1][1] = c12211;
coeff5[1][2][2][1][2] = c12212;
coeff5[1][2][2][1][4] = c12214;
coeff5[1][2][2][1][6] = c12216;
coeff5[1][2][2][2][0] = c12220;
coeff5[1][2][2][2][1] = c12221;
coeff5[1][2][2][2][2] = c12222;
coeff5[1][2][2][2][4] = c12224;
coeff5[2][0][0][0][0] = c20000;
coeff5[2][0][0][0][1] = c20001;
coeff5[2][0][0][0][2] = c20002;
coeff5[2][0][0][0][4] = c20004;
coeff5[2][0][0][0][6] = c20006;
coeff5[2][0][0][1][0] = c20010;
coeff5[2][0][0][1][1] = c20011;
coeff5[2][0][0][1][2] = c20012;
coeff5[2][0][0][1][4] = c20014;
coeff5[2][0][0][1][6] = c20016;
coeff5[2][0][0][2][0] = c20020;
coeff5[2][0][0][2][1] = c20021;
coeff5[2][0][0][2][2] = c20022;
coeff5[2][0][0][2][4] = c20024;
coeff5[2][0][0][2][6] = c20026;
coeff5[2][0][1][0][0] = c20100;
coeff5[2][0][1][0][1] = c20101;
coeff5[2][0][1][0][2] = c20102;
coeff5[2][0][1][0][4] = c20104;
coeff5[2][0][1][0][6] = c20106;
coeff5[2][0][1][1][0] = c20110;
coeff5[2][0][1][1][1] = c20111;
coeff5[2][0][1][1][2] = c20112;
coeff5[2][0][1][1][4] = c20114;
coeff5[2][0][1][1][6] = c20116;
coeff5[2][0][1][2][0] = c20120;
coeff5[2][0][1][2][1] = c20121;
coeff5[2][0][1][2][2] = c20122;
coeff5[2][0][1][2][4] = c20124;
coeff5[2][0][1][2][6] = c20126;
coeff5[2][0][2][0][0] = c20200;
coeff5[2][0][2][0][1] = c20201;
coeff5[2][0][2][0][2] = c20202;
coeff5[2][0][2][0][4] = c20204;
coeff5[2][0][2][0][6] = c20206;
coeff5[2][0][2][1][0] = c20210;
coeff5[2][0][2][1][1] = c20211;
coeff5[2][0][2][1][2] = c20212;
coeff5[2][0][2][1][4] = c20214;
coeff5[2][0][2][1][6] = c20216;
coeff5[2][0][2][2][0] = c20220;
coeff5[2][0][2][2][1] = c20221;
coeff5[2][0][2][2][2] = c20222;
coeff5[2][0][2][2][4] = c20224;
coeff5[2][0][2][2][6] = c20226;
coeff5[2][1][0][0][0] = c21000;
coeff5[2][1][0][0][1] = c21001;
coeff5[2][1][0][0][2] = c21002;
coeff5[2][1][0][0][4] = c21004;
coeff5[2][1][0][0][6] = c21006;
coeff5[2][1][0][1][0] = c21010;
coeff5[2][1][0][1][1] = c21011;
coeff5[2][1][0][1][2] = c21012;
coeff5[2][1][0][1][4] = c21014;
coeff5[2][1][0][1][6] = c21016;
coeff5[2][1][0][2][0] = c21020;
coeff5[2][1][0][2][1] = c21021;
coeff5[2][1][0][2][2] = c21022;
coeff5[2][1][0][2][4] = c21024;
coeff5[2][1][0][2][6] = c21026;
coeff5[2][1][1][0][0] = c21100;
coeff5[2][1][1][0][1] = c21101;
coeff5[2][1][1][0][2] = c21102;
coeff5[2][1][1][0][4] = c21104;
coeff5[2][1][1][0][6] = c21106;
coeff5[2][1][1][1][0] = c21110;
coeff5[2][1][1][1][1] = c21111;
coeff5[2][1][1][1][2] = c21112;
coeff5[2][1][1][1][4] = c21114;
coeff5[2][1][1][1][6] = c21116;
coeff5[2][1][1][2][0] = c21120;
coeff5[2][1][1][2][1] = c21121;
coeff5[2][1][1][2][2] = c21122;
coeff5[2][1][1][2][4] = c21124;
coeff5[2][1][1][2][6] = c21126;
coeff5[2][1][2][0][0] = c21200;
coeff5[2][1][2][0][1] = c21201;
coeff5[2][1][2][0][2] = c21202;
coeff5[2][1][2][0][4] = c21204;
coeff5[2][1][2][0][6] = c21206;
coeff5[2][1][2][1][0] = c21210;
coeff5[2][1][2][1][1] = c21211;
coeff5[2][1][2][1][2] = c21212;
coeff5[2][1][2][1][4] = c21214;
coeff5[2][1][2][1][6] = c21216;
coeff5[2][1][2][2][0] = c21220;
coeff5[2][1][2][2][1] = c21221;
coeff5[2][1][2][2][2] = c21222;
coeff5[2][1][2][2][4] = c21224;
coeff5[2][2][0][0][0] = c22000;
coeff5[2][2][0][0][1] = c22001;
coeff5[2][2][0][0][2] = c22002;
coeff5[2][2][0][0][4] = c22004;
coeff5[2][2][0][0][6] = c22006;
coeff5[2][2][0][1][0] = c22010;
coeff5[2][2][0][1][1] = c22011;
coeff5[2][2][0][1][2] = c22012;
coeff5[2][2][0][1][4] = c22014;
coeff5[2][2][0][1][6] = c22016;
coeff5[2][2][0][2][0] = c22020;
coeff5[2][2][0][2][1] = c22021;
coeff5[2][2][0][2][2] = c22022;
coeff5[2][2][0][2][4] = c22024;
coeff5[2][2][0][2][6] = c22026;
coeff5[2][2][1][0][0] = c22100;
coeff5[2][2][1][0][1] = c22101;
coeff5[2][2][1][0][2] = c22102;
coeff5[2][2][1][0][4] = c22104;
coeff5[2][2][1][0][6] = c22106;
coeff5[2][2][1][1][0] = c22110;
coeff5[2][2][1][1][1] = c22111;
coeff5[2][2][1][1][2] = c22112;
coeff5[2][2][1][1][4] = c22114;
coeff5[2][2][1][1][6] = c22116;
coeff5[2][2][1][2][0] = c22120;
coeff5[2][2][1][2][1] = c22121;
coeff5[2][2][1][2][2] = c22122;
coeff5[2][2][1][2][4] = c22124;
coeff5[2][2][2][0][0] = c22200;
coeff5[2][2][2][0][1] = c22201;
coeff5[2][2][2][0][2] = c22202;
coeff5[2][2][2][0][4] = c22204;
coeff5[2][2][2][0][6] = c22206;
coeff5[2][2][2][1][0] = c22210;
coeff5[2][2][2][1][1] = c22211;
coeff5[2][2][2][1][2] = c22212;
coeff5[2][2][2][1][4] = c22214;
coeff5[2][2][2][2][0] = c22220;
coeff5[2][2][2][2][1] = c22221;
coeff5[2][2][2][2][2] = c22222;
coeff5[2][2][2][2][4] = c22224;

     Double_t val[5][2];
     Double_t result=0.;

     switch(code) {
     case 1: 
       val[0][0]=costheta0.min();
       val[0][1]=costheta0.max();
       val[1][0]=costheta1.min();
       val[1][1]=costheta1.max();
       val[2][0]=costheta2.min();
       val[2][1]=costheta2.max();
       val[3][0]=phi1.min();
       val[3][1]=phi1.max();
       val[4][0]=phi2.min();
       val[4][1]=phi2.max();
       

       for (int a=0; a<=1; a++) {
	 for (int b=0; b<=1; b++) {
	   for (int c=0; c<=1; c++) {
	     for (int d=0; d<=1; d++) {
	       for (int e=0; e<=1; e++) {
		 result= result + pow(-1., a+b+c+d+e+1) * primitiveval5f5(val[0][a],val[1][b],val[2][c],val[3][d],val[4][e],coeff5);
	       }
	     }
	   }
	 }
       }
       
       return result;
       break;
       
     case 2://for costheta0
       val[0][0]=costheta1.min();
       val[0][1]=costheta1.max();
       val[1][0]=costheta2.min();
       val[1][1]=costheta2.max();
       val[2][0]=phi1.min();
       val[2][1]=phi1.max();
       val[3][0]=phi2.min();
       val[3][1]=phi2.max();
       for (int a=0; a<=1; a++) {
	 for (int b=0; b<=1; b++) {
	   for (int c=0; c<=1; c++) {
	     for (int d=0; d<=1; d++) {
	       result= result + pow(-1., a+b+c+d) * primitivedcostheta0val5f5(costheta0,val[0][a],val[1][b],val[2][c],val[3][d],coeff5);
	     }
	   }
	 }
       }
       return result;
       break;

     case 3://for costheta1
       val[0][0]=costheta0.min();
       val[0][1]=costheta0.max();
       val[1][0]=costheta2.min();
       val[1][1]=costheta2.max();
       val[2][0]=phi1.min();
       val[2][1]=phi1.max();
       val[3][0]=phi2.min();
       val[3][1]=phi2.max();
       for (int a=0; a<=1; a++) {
	 for (int b=0; b<=1; b++) {
	   for (int c=0; c<=1; c++) {
	     for (int d=0; d<=1; d++) {
	       result= result + pow(-1., a+b+c+d) * primitivedcostheta1val5f5(val[0][a],costheta1,val[1][b],val[2][c],val[3][d],coeff5);
	     }
	   }
	 }
       }
       return result;
       break;

     case 4://for costheta2
       val[0][0]=costheta0.min();
       val[0][1]=costheta0.max();
       val[1][0]=costheta1.min();
       val[1][1]=costheta1.max();
       val[2][0]=phi1.min();
       val[2][1]=phi1.max();
       val[3][0]=phi2.min();
       val[3][1]=phi2.max();
       for (int a=0; a<=1; a++) {
	 for (int b=0; b<=1; b++) {
	   for (int c=0; c<=1; c++) {
	     for (int d=0; d<=1; d++) {
	       result= result + pow(-1., a+b+c+d) * primitivedcostheta2val5f5(val[0][a],val[1][b],costheta2,val[2][c],val[3][d],coeff5);
	     }
	   }
	 }
       }
       return result;
       break;




     case 5://for phi1
       val[0][0]=costheta0.min();
       val[0][1]=costheta0.max();
       val[1][0]=costheta1.min();
       val[1][1]=costheta1.max();
       val[2][0]=costheta2.min();
       val[2][1]=costheta2.max();
       val[3][0]=phi2.min();
       val[3][1]=phi2.max();
       for (int a=0; a<=1; a++) {
	 for (int b=0; b<=1; b++) {
	   for (int c=0; c<=1; c++) {
	     for (int d=0; d<=1; d++) {
	       result= result + pow(-1., a+b+c+d) * primitivedphi1val5f5(val[0][a],val[1][b],val[2][c],phi1,val[3][d],coeff5);
	     }
	   }
	 }
       }
       return result;
       break;
       
       
     case 6://for phi2
       val[0][0]=costheta0.min();
       val[0][1]=costheta0.max();
       val[1][0]=costheta1.min();
       val[1][1]=costheta1.max();
       val[2][0]=costheta2.min();
       val[2][1]=costheta2.max();
       val[3][0]=phi1.min();
       val[3][1]=phi1.max();
       for (int a=0; a<=1; a++) {
	 for (int b=0; b<=1; b++) {
	   for (int c=0; c<=1; c++) {
	     for (int d=0; d<=1; d++) {
	       result= result + pow(-1., a+b+c+d) * primitivedphi2val5f5(val[0][a],val[1][b],val[2][c],val[3][d],phi2,coeff5);
	     }
	   }
	 }
       }
       return result;
       break;
       
     }

     return 0 ; 

 } 



