/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooLegendre3.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooLegendre3) 

 RooLegendre3::RooLegendre3(const char *name, const char *title, 
                        RooAbsReal& _RooLegendre3) :
   RooAbsReal(name,title), 
   RooLegendre3("RooLegendre3","RooLegendre3",this,_RooLegendre3)
 { 
 } 


 RooLegendre3::RooLegendre3(const RooLegendre3& other, const char* name) :  
   RooAbsReal(other,name), 
   RooLegendre3("RooLegendre3",this,other.RooLegendre3)
 { 
 } 



 Double_t RooLegendre3::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1.0 ; 
 } 



