/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooMyPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooMyPdf) 

 RooMyPdf::RooMyPdf(const char *name, const char *title, 
                        RooAbsReal& _costheta0,
                        RooAbsReal& _costheta1,
                        RooAbsReal& _costheta2,
                        RooAbsReal& _phi1,
                        RooAbsReal& _phi2,
                        RooAbsReal& _c00000,
                        RooAbsReal& _c00001,
                        RooAbsReal& _c00010,
                        RooAbsReal& _c00011,
                        RooAbsReal& _c00100,
                        RooAbsReal& _c00101,
                        RooAbsReal& _c00110,
                        RooAbsReal& _c00111,
                        RooAbsReal& _c01000,
                        RooAbsReal& _c01001,
                        RooAbsReal& _c01010,
                        RooAbsReal& _c01011,
                        RooAbsReal& _c01100,
                        RooAbsReal& _c01101,
                        RooAbsReal& _c01110,
                        RooAbsReal& _c01111,
                        RooAbsReal& _c10000,
                        RooAbsReal& _c10001,
                        RooAbsReal& _c10010,
                        RooAbsReal& _c10011,
                        RooAbsReal& _c10100,
                        RooAbsReal& _c10101,
                        RooAbsReal& _c10110,
                        RooAbsReal& _c10111,
                        RooAbsReal& _c11000,
                        RooAbsReal& _c11001,
                        RooAbsReal& _c11010,
                        RooAbsReal& _c11011,
                        RooAbsReal& _c11100,
                        RooAbsReal& _c11101,
                        RooAbsReal& _c11110,
                        RooAbsReal& _c11111) :
   RooAbsPdf(name,title), 
   costheta0("costheta0","costheta0",this,_costheta0),
   costheta1("costheta1","costheta1",this,_costheta1),
   costheta2("costheta2","costheta2",this,_costheta2),
   phi1("phi1","phi1",this,_phi1),
   phi2("phi2","phi2",this,_phi2),
   c00000("c00000","c00000",this,_c00000),
   c00001("c00001","c00001",this,_c00001),
   c00010("c00010","c00010",this,_c00010),
   c00011("c00011","c00011",this,_c00011),
   c00100("c00100","c00100",this,_c00100),
   c00101("c00101","c00101",this,_c00101),
   c00110("c00110","c00110",this,_c00110),
   c00111("c00111","c00111",this,_c00111),
   c01000("c01000","c01000",this,_c01000),
   c01001("c01001","c01001",this,_c01001),
   c01010("c01010","c01010",this,_c01010),
   c01011("c01011","c01011",this,_c01011),
   c01100("c01100","c01100",this,_c01100),
   c01101("c01101","c01101",this,_c01101),
   c01110("c01110","c01110",this,_c01110),
   c01111("c01111","c01111",this,_c01111),
   c10000("c10000","c10000",this,_c10000),
   c10001("c10001","c10001",this,_c10001),
   c10010("c10010","c10010",this,_c10010),
   c10011("c10011","c10011",this,_c10011),
   c10100("c10100","c10100",this,_c10100),
   c10101("c10101","c10101",this,_c10101),
   c10110("c10110","c10110",this,_c10110),
   c10111("c10111","c10111",this,_c10111),
   c11000("c11000","c11000",this,_c11000),
   c11001("c11001","c11001",this,_c11001),
   c11010("c11010","c11010",this,_c11010),
   c11011("c11011","c11011",this,_c11011),
   c11100("c11100","c11100",this,_c11100),
   c11101("c11101","c11101",this,_c11101),
   c11110("c11110","c11110",this,_c11110),
   c11111("c11111","c11111",this,_c11111)
 { 
 } 


 RooMyPdf::RooMyPdf(const RooMyPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   costheta0("costheta0",this,other.costheta0),
   costheta1("costheta1",this,other.costheta1),
   costheta2("costheta2",this,other.costheta2),
   phi1("phi1",this,other.phi1),
   phi2("phi2",this,other.phi2),
   c00000("c00000",this,other.c00000),
   c00001("c00001",this,other.c00001),
   c00010("c00010",this,other.c00010),
   c00011("c00011",this,other.c00011),
   c00100("c00100",this,other.c00100),
   c00101("c00101",this,other.c00101),
   c00110("c00110",this,other.c00110),
   c00111("c00111",this,other.c00111),
   c01000("c01000",this,other.c01000),
   c01001("c01001",this,other.c01001),
   c01010("c01010",this,other.c01010),
   c01011("c01011",this,other.c01011),
   c01100("c01100",this,other.c01100),
   c01101("c01101",this,other.c01101),
   c01110("c01110",this,other.c01110),
   c01111("c01111",this,other.c01111),
   c10000("c10000",this,other.c10000),
   c10001("c10001",this,other.c10001),
   c10010("c10010",this,other.c10010),
   c10011("c10011",this,other.c10011),
   c10100("c10100",this,other.c10100),
   c10101("c10101",this,other.c10101),
   c10110("c10110",this,other.c10110),
   c10111("c10111",this,other.c10111),
   c11000("c11000",this,other.c11000),
   c11001("c11001",this,other.c11001),
   c11010("c11010",this,other.c11010),
   c11011("c11011",this,other.c11011),
   c11100("c11100",this,other.c11100),
   c11101("c11101",this,other.c11101),
   c11110("c11110",this,other.c11110),
   c11111("c11111",this,other.c11111)
 { 
 } 



 Double_t RooMyPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return sqrt(abs(x*alpha))+0.1 ; 
 } 



