/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOLEGENDRE3PDFV2
#define ROOLEGENDRE3PDFV2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooListProxy.h"
#include "legendre2f2.h"
#include "functions.h"

class RooLegendre2Pdf : public RooAbsPdf {
public:
  RooLegendre2Pdf() {} ; 
  RooLegendre2Pdf(const char *name, const char *title,
		    RooAbsReal& _phi1,
		    RooAbsReal& _phi2,
		    RooArgList& _varlist);

  RooLegendre2Pdf(const RooLegendre2Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooLegendre2Pdf(*this,newname); }
  inline virtual ~RooLegendre2Pdf() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:
  Double_t evaluate() const ;

  RooRealProxy phi1 ;
  RooRealProxy phi2 ;
  RooListProxy varlist;

private:
  ClassDef(RooLegendre2Pdf,1) // Your description goes here...
};
 
#endif
