/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOLEGENDRE3
#define ROOLEGENDRE3

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooLegendre3 : public RooAbsReal {
public:
  RooLegendre3() {} ; 
  RooLegendre3(const char *name, const char *title,
	      RooAbsReal& _RooLegendre3);
  RooLegendre3(const RooLegendre3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooLegendre3(*this,newname); }
  inline virtual ~RooLegendre3() { }

protected:

  RooRealProxy RooLegendre3 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooLegendre3,1) // Your description goes here...
};
 
#endif
