/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOLEGENDRE3PDF
#define ROOLEGENDRE3PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooLegendre3Pdf : public RooAbsPdf {
public:
  RooLegendre3Pdf() {} ; 
  RooLegendre3Pdf(const char *name, const char *title,
	      RooAbsReal& _costheta0,
	      RooAbsReal& _costheta1,
	      RooAbsReal& _costheta2,
	      RooAbsReal& _c000,
	      RooAbsReal& _c001,
	      RooAbsReal& _c002,
	      RooAbsReal& _c004,
	      RooAbsReal& _c006,
	      RooAbsReal& _c010,
	      RooAbsReal& _c011,
	      RooAbsReal& _c012,
	      RooAbsReal& _c014,
	      RooAbsReal& _c016,
	      RooAbsReal& _c020,
	      RooAbsReal& _c021,
	      RooAbsReal& _c022,
	      RooAbsReal& _c024,
	      RooAbsReal& _c026,
	      RooAbsReal& _c100,
	      RooAbsReal& _c101,
	      RooAbsReal& _c102,
	      RooAbsReal& _c104,
	      RooAbsReal& _c106,
	      RooAbsReal& _c110,
	      RooAbsReal& _c111,
	      RooAbsReal& _c112,
	      RooAbsReal& _c114,
	      RooAbsReal& _c116,
	      RooAbsReal& _c120,
	      RooAbsReal& _c121,
	      RooAbsReal& _c122,
	      RooAbsReal& _c124,
	      RooAbsReal& _c126,
	      RooAbsReal& _c200,
	      RooAbsReal& _c201,
	      RooAbsReal& _c202,
	      RooAbsReal& _c204,
	      RooAbsReal& _c206,
	      RooAbsReal& _c210,
	      RooAbsReal& _c211,
	      RooAbsReal& _c212,
	      RooAbsReal& _c214,
	      RooAbsReal& _c216,
	      RooAbsReal& _c220,
	      RooAbsReal& _c221,
	      RooAbsReal& _c222,
	      RooAbsReal& _c224,
	      RooAbsReal& _c226);
  RooLegendre3Pdf(const RooLegendre3Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooLegendre3Pdf(*this,newname); }
  inline virtual ~RooLegendre3Pdf() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy costheta0 ;
  RooRealProxy costheta1 ;
  RooRealProxy costheta2 ;
  RooRealProxy c000 ;
  RooRealProxy c001 ;
  RooRealProxy c002 ;
  RooRealProxy c004 ;
  RooRealProxy c006 ;
  RooRealProxy c010 ;
  RooRealProxy c011 ;
  RooRealProxy c012 ;
  RooRealProxy c014 ;
  RooRealProxy c016 ;
  RooRealProxy c020 ;
  RooRealProxy c021 ;
  RooRealProxy c022 ;
  RooRealProxy c024 ;
  RooRealProxy c026 ;
  RooRealProxy c100 ;
  RooRealProxy c101 ;
  RooRealProxy c102 ;
  RooRealProxy c104 ;
  RooRealProxy c106 ;
  RooRealProxy c110 ;
  RooRealProxy c111 ;
  RooRealProxy c112 ;
  RooRealProxy c114 ;
  RooRealProxy c116 ;
  RooRealProxy c120 ;
  RooRealProxy c121 ;
  RooRealProxy c122 ;
  RooRealProxy c124 ;
  RooRealProxy c126 ;
  RooRealProxy c200 ;
  RooRealProxy c201 ;
  RooRealProxy c202 ;
  RooRealProxy c204 ;
  RooRealProxy c206 ;
  RooRealProxy c210 ;
  RooRealProxy c211 ;
  RooRealProxy c212 ;
  RooRealProxy c214 ;
  RooRealProxy c216 ;
  RooRealProxy c220 ;
  RooRealProxy c221 ;
  RooRealProxy c222 ;
  RooRealProxy c224 ;
  RooRealProxy c226 ;
  
  Double_t evaluate() const ;

  static const int ordermaxi=4;
  static const int ordermaxj=4;
  static const int ordermaxk=7;

private:

  ClassDef(RooLegendre3Pdf,1) // Your description goes here...
};
 
#endif
