/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOLEGENDRE3PDFV2
#define ROOLEGENDRE3PDFV2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooListProxy.h"
#include "legendre3f3.h"
#include "functions.h"

class RooLegendre3Pdfv2 : public RooAbsPdf {
public:
  RooLegendre3Pdfv2() {} ; 
  RooLegendre3Pdfv2(const char *name, const char *title,
		    RooAbsReal& _costheta0,
		    RooAbsReal& _costheta1,
		    RooAbsReal& _costheta2,
		    RooArgList& _varlist);

  RooLegendre3Pdfv2(const RooLegendre3Pdfv2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooLegendre3Pdfv2(*this,newname); }
  inline virtual ~RooLegendre3Pdfv2() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:
  Double_t evaluate() const ;

  RooRealProxy costheta0 ;
  RooRealProxy costheta1 ;
  RooRealProxy costheta2 ;
  RooListProxy varlist;

private:
  ClassDef(RooLegendre3Pdfv2,1) // Your description goes here...
};
 
#endif
