/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOLEGENDRE5PDF
#define ROOLEGENDRE5PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooLegendre5Pdf : public RooAbsPdf {
public:
  RooLegendre5Pdf() {} ; 
  RooLegendre5Pdf(const char *name, const char *title,
	      RooAbsReal& _costheta0,
	      RooAbsReal& _costheta1,
	      RooAbsReal& _costheta2,
	      RooAbsReal& _phi1,
	      RooAbsReal& _phi2,
	      RooAbsReal& _c00000,
	      RooAbsReal& _c00001,
	      RooAbsReal& _c00002,
	      RooAbsReal& _c00004,
	      RooAbsReal& _c00006,
	      RooAbsReal& _c00010,
	      RooAbsReal& _c00011,
	      RooAbsReal& _c00012,
	      RooAbsReal& _c00014,
	      RooAbsReal& _c00016,
	      RooAbsReal& _c00020,
	      RooAbsReal& _c00021,
	      RooAbsReal& _c00022,
	      RooAbsReal& _c00024,
	      RooAbsReal& _c00026,
	      RooAbsReal& _c00100,
	      RooAbsReal& _c00101,
	      RooAbsReal& _c00102,
	      RooAbsReal& _c00104,
	      RooAbsReal& _c00106,
	      RooAbsReal& _c00110,
	      RooAbsReal& _c00111,
	      RooAbsReal& _c00112,
	      RooAbsReal& _c00114,
	      RooAbsReal& _c00116,
	      RooAbsReal& _c00120,
	      RooAbsReal& _c00121,
	      RooAbsReal& _c00122,
	      RooAbsReal& _c00124,
	      RooAbsReal& _c00126,
	      RooAbsReal& _c00200,
	      RooAbsReal& _c00201,
	      RooAbsReal& _c00202,
	      RooAbsReal& _c00204,
	      RooAbsReal& _c00206,
	      RooAbsReal& _c00210,
	      RooAbsReal& _c00211,
	      RooAbsReal& _c00212,
	      RooAbsReal& _c00214,
	      RooAbsReal& _c00216,
	      RooAbsReal& _c00220,
	      RooAbsReal& _c00221,
	      RooAbsReal& _c00222,
	      RooAbsReal& _c00224,
	      RooAbsReal& _c00226,
	      RooAbsReal& _c01000,
	      RooAbsReal& _c01001,
	      RooAbsReal& _c01002,
	      RooAbsReal& _c01004,
	      RooAbsReal& _c01006,
	      RooAbsReal& _c01010,
	      RooAbsReal& _c01011,
	      RooAbsReal& _c01012,
	      RooAbsReal& _c01014,
	      RooAbsReal& _c01016,
	      RooAbsReal& _c01020,
	      RooAbsReal& _c01021,
	      RooAbsReal& _c01022,
	      RooAbsReal& _c01024,
	      RooAbsReal& _c01026,
	      RooAbsReal& _c01100,
	      RooAbsReal& _c01101,
	      RooAbsReal& _c01102,
	      RooAbsReal& _c01104,
	      RooAbsReal& _c01106,
	      RooAbsReal& _c01110,
	      RooAbsReal& _c01111,
	      RooAbsReal& _c01112,
	      RooAbsReal& _c01114,
	      RooAbsReal& _c01116,
	      RooAbsReal& _c01120,
	      RooAbsReal& _c01121,
	      RooAbsReal& _c01122,
	      RooAbsReal& _c01124,
	      RooAbsReal& _c01126,
	      RooAbsReal& _c01200,
	      RooAbsReal& _c01201,
	      RooAbsReal& _c01202,
	      RooAbsReal& _c01204,
	      RooAbsReal& _c01206,
	      RooAbsReal& _c01210,
	      RooAbsReal& _c01211,
	      RooAbsReal& _c01212,
	      RooAbsReal& _c01214,
	      RooAbsReal& _c01216,
	      RooAbsReal& _c01220,
	      RooAbsReal& _c01221,
	      RooAbsReal& _c01222,
	      RooAbsReal& _c01224,
	      RooAbsReal& _c01226,
	      RooAbsReal& _c02000,
	      RooAbsReal& _c02001,
	      RooAbsReal& _c02002,
	      RooAbsReal& _c02004,
	      RooAbsReal& _c02006,
	      RooAbsReal& _c02010,
	      RooAbsReal& _c02011,
	      RooAbsReal& _c02012,
	      RooAbsReal& _c02014,
	      RooAbsReal& _c02016,
	      RooAbsReal& _c02020,
	      RooAbsReal& _c02021,
	      RooAbsReal& _c02022,
	      RooAbsReal& _c02024,
	      RooAbsReal& _c02026,
	      RooAbsReal& _c02100,
	      RooAbsReal& _c02101,
	      RooAbsReal& _c02102,
	      RooAbsReal& _c02104,
	      RooAbsReal& _c02106,
	      RooAbsReal& _c02110,
	      RooAbsReal& _c02111,
	      RooAbsReal& _c02112,
	      RooAbsReal& _c02114,
	      RooAbsReal& _c02116,
	      RooAbsReal& _c02120,
	      RooAbsReal& _c02121,
	      RooAbsReal& _c02122,
	      RooAbsReal& _c02124,
	      RooAbsReal& _c02126,
	      RooAbsReal& _c02200,
	      RooAbsReal& _c02201,
	      RooAbsReal& _c02202,
	      RooAbsReal& _c02204,
	      RooAbsReal& _c02206,
	      RooAbsReal& _c02210,
	      RooAbsReal& _c02211,
	      RooAbsReal& _c02212,
	      RooAbsReal& _c02214,
	      RooAbsReal& _c02216,
	      RooAbsReal& _c02220,
	      RooAbsReal& _c02221,
	      RooAbsReal& _c02222,
	      RooAbsReal& _c02224,
	      RooAbsReal& _c02226,
	      RooAbsReal& _c10000,
	      RooAbsReal& _c10001,
	      RooAbsReal& _c10002,
	      RooAbsReal& _c10004,
	      RooAbsReal& _c10006,
	      RooAbsReal& _c10010,
	      RooAbsReal& _c10011,
	      RooAbsReal& _c10012,
	      RooAbsReal& _c10014,
	      RooAbsReal& _c10016,
	      RooAbsReal& _c10020,
	      RooAbsReal& _c10021,
	      RooAbsReal& _c10022,
	      RooAbsReal& _c10024,
	      RooAbsReal& _c10026,
	      RooAbsReal& _c10100,
	      RooAbsReal& _c10101,
	      RooAbsReal& _c10102,
	      RooAbsReal& _c10104,
	      RooAbsReal& _c10106,
	      RooAbsReal& _c10110,
	      RooAbsReal& _c10111,
	      RooAbsReal& _c10112,
	      RooAbsReal& _c10114,
	      RooAbsReal& _c10116,
	      RooAbsReal& _c10120,
	      RooAbsReal& _c10121,
	      RooAbsReal& _c10122,
	      RooAbsReal& _c10124,
	      RooAbsReal& _c10126,
	      RooAbsReal& _c10200,
	      RooAbsReal& _c10201,
	      RooAbsReal& _c10202,
	      RooAbsReal& _c10204,
	      RooAbsReal& _c10206,
	      RooAbsReal& _c10210,
	      RooAbsReal& _c10211,
	      RooAbsReal& _c10212,
	      RooAbsReal& _c10214,
	      RooAbsReal& _c10216,
	      RooAbsReal& _c10220,
	      RooAbsReal& _c10221,
	      RooAbsReal& _c10222,
	      RooAbsReal& _c10224,
	      RooAbsReal& _c10226,
	      RooAbsReal& _c11000,
	      RooAbsReal& _c11001,
	      RooAbsReal& _c11002,
	      RooAbsReal& _c11004,
	      RooAbsReal& _c11006,
	      RooAbsReal& _c11010,
	      RooAbsReal& _c11011,
	      RooAbsReal& _c11012,
	      RooAbsReal& _c11014,
	      RooAbsReal& _c11016,
	      RooAbsReal& _c11020,
	      RooAbsReal& _c11021,
	      RooAbsReal& _c11022,
	      RooAbsReal& _c11024,
	      RooAbsReal& _c11026,
	      RooAbsReal& _c11100,
	      RooAbsReal& _c11101,
	      RooAbsReal& _c11102,
	      RooAbsReal& _c11104,
	      RooAbsReal& _c11106,
	      RooAbsReal& _c11110,
	      RooAbsReal& _c11111,
	      RooAbsReal& _c11112,
	      RooAbsReal& _c11114,
	      RooAbsReal& _c11116,
	      RooAbsReal& _c11120,
	      RooAbsReal& _c11121,
	      RooAbsReal& _c11122,
	      RooAbsReal& _c11124,
	      RooAbsReal& _c11126,
	      RooAbsReal& _c11200,
	      RooAbsReal& _c11201,
	      RooAbsReal& _c11202,
	      RooAbsReal& _c11204,
	      RooAbsReal& _c11206,
	      RooAbsReal& _c11210,
	      RooAbsReal& _c11211,
	      RooAbsReal& _c11212,
	      RooAbsReal& _c11214,
	      RooAbsReal& _c11216,
	      RooAbsReal& _c11220,
	      RooAbsReal& _c11221,
	      RooAbsReal& _c11222,
	      RooAbsReal& _c11224,
	      RooAbsReal& _c11226,
	      RooAbsReal& _c12000,
	      RooAbsReal& _c12001,
	      RooAbsReal& _c12002,
	      RooAbsReal& _c12004,
	      RooAbsReal& _c12006,
	      RooAbsReal& _c12010,
	      RooAbsReal& _c12011,
	      RooAbsReal& _c12012,
	      RooAbsReal& _c12014,
	      RooAbsReal& _c12016,
	      RooAbsReal& _c12020,
	      RooAbsReal& _c12021,
	      RooAbsReal& _c12022,
	      RooAbsReal& _c12024,
	      RooAbsReal& _c12026,
	      RooAbsReal& _c12100,
	      RooAbsReal& _c12101,
	      RooAbsReal& _c12102,
	      RooAbsReal& _c12104,
	      RooAbsReal& _c12106,
	      RooAbsReal& _c12110,
	      RooAbsReal& _c12111,
	      RooAbsReal& _c12112,
	      RooAbsReal& _c12114,
	      RooAbsReal& _c12116,
	      RooAbsReal& _c12120,
	      RooAbsReal& _c12121,
	      RooAbsReal& _c12122,
	      RooAbsReal& _c12124,
	      RooAbsReal& _c12126,
	      RooAbsReal& _c12200,
	      RooAbsReal& _c12201,
	      RooAbsReal& _c12202,
	      RooAbsReal& _c12204,
	      RooAbsReal& _c12206,
	      RooAbsReal& _c12210,
	      RooAbsReal& _c12211,
	      RooAbsReal& _c12212,
	      RooAbsReal& _c12214,
	      RooAbsReal& _c12216,
	      RooAbsReal& _c12220,
	      RooAbsReal& _c12221,
	      RooAbsReal& _c12222,
	      RooAbsReal& _c12224,
	      RooAbsReal& _c20000,
	      RooAbsReal& _c20001,
	      RooAbsReal& _c20002,
	      RooAbsReal& _c20004,
	      RooAbsReal& _c20006,
	      RooAbsReal& _c20010,
	      RooAbsReal& _c20011,
	      RooAbsReal& _c20012,
	      RooAbsReal& _c20014,
	      RooAbsReal& _c20016,
	      RooAbsReal& _c20020,
	      RooAbsReal& _c20021,
	      RooAbsReal& _c20022,
	      RooAbsReal& _c20024,
	      RooAbsReal& _c20026,
	      RooAbsReal& _c20100,
	      RooAbsReal& _c20101,
	      RooAbsReal& _c20102,
	      RooAbsReal& _c20104,
	      RooAbsReal& _c20106,
	      RooAbsReal& _c20110,
	      RooAbsReal& _c20111,
	      RooAbsReal& _c20112,
	      RooAbsReal& _c20114,
	      RooAbsReal& _c20116,
	      RooAbsReal& _c20120,
	      RooAbsReal& _c20121,
	      RooAbsReal& _c20122,
	      RooAbsReal& _c20124,
	      RooAbsReal& _c20126,
	      RooAbsReal& _c20200,
	      RooAbsReal& _c20201,
	      RooAbsReal& _c20202,
	      RooAbsReal& _c20204,
	      RooAbsReal& _c20206,
	      RooAbsReal& _c20210,
	      RooAbsReal& _c20211,
	      RooAbsReal& _c20212,
	      RooAbsReal& _c20214,
	      RooAbsReal& _c20216,
	      RooAbsReal& _c20220,
	      RooAbsReal& _c20221,
	      RooAbsReal& _c20222,
	      RooAbsReal& _c20224,
	      RooAbsReal& _c20226,
	      RooAbsReal& _c21000,
	      RooAbsReal& _c21001,
	      RooAbsReal& _c21002,
	      RooAbsReal& _c21004,
	      RooAbsReal& _c21006,
	      RooAbsReal& _c21010,
	      RooAbsReal& _c21011,
	      RooAbsReal& _c21012,
	      RooAbsReal& _c21014,
	      RooAbsReal& _c21016,
	      RooAbsReal& _c21020,
	      RooAbsReal& _c21021,
	      RooAbsReal& _c21022,
	      RooAbsReal& _c21024,
	      RooAbsReal& _c21026,
	      RooAbsReal& _c21100,
	      RooAbsReal& _c21101,
	      RooAbsReal& _c21102,
	      RooAbsReal& _c21104,
	      RooAbsReal& _c21106,
	      RooAbsReal& _c21110,
	      RooAbsReal& _c21111,
	      RooAbsReal& _c21112,
	      RooAbsReal& _c21114,
	      RooAbsReal& _c21116,
	      RooAbsReal& _c21120,
	      RooAbsReal& _c21121,
	      RooAbsReal& _c21122,
	      RooAbsReal& _c21124,
	      RooAbsReal& _c21126,
	      RooAbsReal& _c21200,
	      RooAbsReal& _c21201,
	      RooAbsReal& _c21202,
	      RooAbsReal& _c21204,
	      RooAbsReal& _c21206,
	      RooAbsReal& _c21210,
	      RooAbsReal& _c21211,
	      RooAbsReal& _c21212,
	      RooAbsReal& _c21214,
	      RooAbsReal& _c21216,
	      RooAbsReal& _c21220,
	      RooAbsReal& _c21221,
	      RooAbsReal& _c21222,
	      RooAbsReal& _c21224,
	      RooAbsReal& _c22000,
	      RooAbsReal& _c22001,
	      RooAbsReal& _c22002,
	      RooAbsReal& _c22004,
	      RooAbsReal& _c22006,
	      RooAbsReal& _c22010,
	      RooAbsReal& _c22011,
	      RooAbsReal& _c22012,
	      RooAbsReal& _c22014,
	      RooAbsReal& _c22016,
	      RooAbsReal& _c22020,
	      RooAbsReal& _c22021,
	      RooAbsReal& _c22022,
	      RooAbsReal& _c22024,
	      RooAbsReal& _c22026,
	      RooAbsReal& _c22100,
	      RooAbsReal& _c22101,
	      RooAbsReal& _c22102,
	      RooAbsReal& _c22104,
	      RooAbsReal& _c22106,
	      RooAbsReal& _c22110,
	      RooAbsReal& _c22111,
	      RooAbsReal& _c22112,
	      RooAbsReal& _c22114,
	      RooAbsReal& _c22116,
	      RooAbsReal& _c22120,
	      RooAbsReal& _c22121,
	      RooAbsReal& _c22122,
	      RooAbsReal& _c22124,
	      RooAbsReal& _c22200,
	      RooAbsReal& _c22201,
	      RooAbsReal& _c22202,
	      RooAbsReal& _c22204,
	      RooAbsReal& _c22206,
	      RooAbsReal& _c22210,
	      RooAbsReal& _c22211,
	      RooAbsReal& _c22212,
	      RooAbsReal& _c22214,
	      RooAbsReal& _c22220,
	      RooAbsReal& _c22221,
	      RooAbsReal& _c22222,
	      RooAbsReal& _c22224);
  RooLegendre5Pdf(const RooLegendre5Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooLegendre5Pdf(*this,newname); }
  inline virtual ~RooLegendre5Pdf() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy costheta0 ;
  RooRealProxy costheta1 ;
  RooRealProxy costheta2 ;
  RooRealProxy phi1 ;
  RooRealProxy phi2 ;
  RooRealProxy c00000 ;
  RooRealProxy c00001 ;
  RooRealProxy c00002 ;
  RooRealProxy c00004 ;
  RooRealProxy c00006 ;
  RooRealProxy c00010 ;
  RooRealProxy c00011 ;
  RooRealProxy c00012 ;
  RooRealProxy c00014 ;
  RooRealProxy c00016 ;
  RooRealProxy c00020 ;
  RooRealProxy c00021 ;
  RooRealProxy c00022 ;
  RooRealProxy c00024 ;
  RooRealProxy c00026 ;
  RooRealProxy c00100 ;
  RooRealProxy c00101 ;
  RooRealProxy c00102 ;
  RooRealProxy c00104 ;
  RooRealProxy c00106 ;
  RooRealProxy c00110 ;
  RooRealProxy c00111 ;
  RooRealProxy c00112 ;
  RooRealProxy c00114 ;
  RooRealProxy c00116 ;
  RooRealProxy c00120 ;
  RooRealProxy c00121 ;
  RooRealProxy c00122 ;
  RooRealProxy c00124 ;
  RooRealProxy c00126 ;
  RooRealProxy c00200 ;
  RooRealProxy c00201 ;
  RooRealProxy c00202 ;
  RooRealProxy c00204 ;
  RooRealProxy c00206 ;
  RooRealProxy c00210 ;
  RooRealProxy c00211 ;
  RooRealProxy c00212 ;
  RooRealProxy c00214 ;
  RooRealProxy c00216 ;
  RooRealProxy c00220 ;
  RooRealProxy c00221 ;
  RooRealProxy c00222 ;
  RooRealProxy c00224 ;
  RooRealProxy c00226 ;
  RooRealProxy c01000 ;
  RooRealProxy c01001 ;
  RooRealProxy c01002 ;
  RooRealProxy c01004 ;
  RooRealProxy c01006 ;
  RooRealProxy c01010 ;
  RooRealProxy c01011 ;
  RooRealProxy c01012 ;
  RooRealProxy c01014 ;
  RooRealProxy c01016 ;
  RooRealProxy c01020 ;
  RooRealProxy c01021 ;
  RooRealProxy c01022 ;
  RooRealProxy c01024 ;
  RooRealProxy c01026 ;
  RooRealProxy c01100 ;
  RooRealProxy c01101 ;
  RooRealProxy c01102 ;
  RooRealProxy c01104 ;
  RooRealProxy c01106 ;
  RooRealProxy c01110 ;
  RooRealProxy c01111 ;
  RooRealProxy c01112 ;
  RooRealProxy c01114 ;
  RooRealProxy c01116 ;
  RooRealProxy c01120 ;
  RooRealProxy c01121 ;
  RooRealProxy c01122 ;
  RooRealProxy c01124 ;
  RooRealProxy c01126 ;
  RooRealProxy c01200 ;
  RooRealProxy c01201 ;
  RooRealProxy c01202 ;
  RooRealProxy c01204 ;
  RooRealProxy c01206 ;
  RooRealProxy c01210 ;
  RooRealProxy c01211 ;
  RooRealProxy c01212 ;
  RooRealProxy c01214 ;
  RooRealProxy c01216 ;
  RooRealProxy c01220 ;
  RooRealProxy c01221 ;
  RooRealProxy c01222 ;
  RooRealProxy c01224 ;
  RooRealProxy c01226 ;
  RooRealProxy c02000 ;
  RooRealProxy c02001 ;
  RooRealProxy c02002 ;
  RooRealProxy c02004 ;
  RooRealProxy c02006 ;
  RooRealProxy c02010 ;
  RooRealProxy c02011 ;
  RooRealProxy c02012 ;
  RooRealProxy c02014 ;
  RooRealProxy c02016 ;
  RooRealProxy c02020 ;
  RooRealProxy c02021 ;
  RooRealProxy c02022 ;
  RooRealProxy c02024 ;
  RooRealProxy c02026 ;
  RooRealProxy c02100 ;
  RooRealProxy c02101 ;
  RooRealProxy c02102 ;
  RooRealProxy c02104 ;
  RooRealProxy c02106 ;
  RooRealProxy c02110 ;
  RooRealProxy c02111 ;
  RooRealProxy c02112 ;
  RooRealProxy c02114 ;
  RooRealProxy c02116 ;
  RooRealProxy c02120 ;
  RooRealProxy c02121 ;
  RooRealProxy c02122 ;
  RooRealProxy c02124 ;
  RooRealProxy c02126 ;
  RooRealProxy c02200 ;
  RooRealProxy c02201 ;
  RooRealProxy c02202 ;
  RooRealProxy c02204 ;
  RooRealProxy c02206 ;
  RooRealProxy c02210 ;
  RooRealProxy c02211 ;
  RooRealProxy c02212 ;
  RooRealProxy c02214 ;
  RooRealProxy c02216 ;
  RooRealProxy c02220 ;
  RooRealProxy c02221 ;
  RooRealProxy c02222 ;
  RooRealProxy c02224 ;
  RooRealProxy c02226 ;
  RooRealProxy c10000 ;
  RooRealProxy c10001 ;
  RooRealProxy c10002 ;
  RooRealProxy c10004 ;
  RooRealProxy c10006 ;
  RooRealProxy c10010 ;
  RooRealProxy c10011 ;
  RooRealProxy c10012 ;
  RooRealProxy c10014 ;
  RooRealProxy c10016 ;
  RooRealProxy c10020 ;
  RooRealProxy c10021 ;
  RooRealProxy c10022 ;
  RooRealProxy c10024 ;
  RooRealProxy c10026 ;
  RooRealProxy c10100 ;
  RooRealProxy c10101 ;
  RooRealProxy c10102 ;
  RooRealProxy c10104 ;
  RooRealProxy c10106 ;
  RooRealProxy c10110 ;
  RooRealProxy c10111 ;
  RooRealProxy c10112 ;
  RooRealProxy c10114 ;
  RooRealProxy c10116 ;
  RooRealProxy c10120 ;
  RooRealProxy c10121 ;
  RooRealProxy c10122 ;
  RooRealProxy c10124 ;
  RooRealProxy c10126 ;
  RooRealProxy c10200 ;
  RooRealProxy c10201 ;
  RooRealProxy c10202 ;
  RooRealProxy c10204 ;
  RooRealProxy c10206 ;
  RooRealProxy c10210 ;
  RooRealProxy c10211 ;
  RooRealProxy c10212 ;
  RooRealProxy c10214 ;
  RooRealProxy c10216 ;
  RooRealProxy c10220 ;
  RooRealProxy c10221 ;
  RooRealProxy c10222 ;
  RooRealProxy c10224 ;
  RooRealProxy c10226 ;
  RooRealProxy c11000 ;
  RooRealProxy c11001 ;
  RooRealProxy c11002 ;
  RooRealProxy c11004 ;
  RooRealProxy c11006 ;
  RooRealProxy c11010 ;
  RooRealProxy c11011 ;
  RooRealProxy c11012 ;
  RooRealProxy c11014 ;
  RooRealProxy c11016 ;
  RooRealProxy c11020 ;
  RooRealProxy c11021 ;
  RooRealProxy c11022 ;
  RooRealProxy c11024 ;
  RooRealProxy c11026 ;
  RooRealProxy c11100 ;
  RooRealProxy c11101 ;
  RooRealProxy c11102 ;
  RooRealProxy c11104 ;
  RooRealProxy c11106 ;
  RooRealProxy c11110 ;
  RooRealProxy c11111 ;
  RooRealProxy c11112 ;
  RooRealProxy c11114 ;
  RooRealProxy c11116 ;
  RooRealProxy c11120 ;
  RooRealProxy c11121 ;
  RooRealProxy c11122 ;
  RooRealProxy c11124 ;
  RooRealProxy c11126 ;
  RooRealProxy c11200 ;
  RooRealProxy c11201 ;
  RooRealProxy c11202 ;
  RooRealProxy c11204 ;
  RooRealProxy c11206 ;
  RooRealProxy c11210 ;
  RooRealProxy c11211 ;
  RooRealProxy c11212 ;
  RooRealProxy c11214 ;
  RooRealProxy c11216 ;
  RooRealProxy c11220 ;
  RooRealProxy c11221 ;
  RooRealProxy c11222 ;
  RooRealProxy c11224 ;
  RooRealProxy c11226 ;
  RooRealProxy c12000 ;
  RooRealProxy c12001 ;
  RooRealProxy c12002 ;
  RooRealProxy c12004 ;
  RooRealProxy c12006 ;
  RooRealProxy c12010 ;
  RooRealProxy c12011 ;
  RooRealProxy c12012 ;
  RooRealProxy c12014 ;
  RooRealProxy c12016 ;
  RooRealProxy c12020 ;
  RooRealProxy c12021 ;
  RooRealProxy c12022 ;
  RooRealProxy c12024 ;
  RooRealProxy c12026 ;
  RooRealProxy c12100 ;
  RooRealProxy c12101 ;
  RooRealProxy c12102 ;
  RooRealProxy c12104 ;
  RooRealProxy c12106 ;
  RooRealProxy c12110 ;
  RooRealProxy c12111 ;
  RooRealProxy c12112 ;
  RooRealProxy c12114 ;
  RooRealProxy c12116 ;
  RooRealProxy c12120 ;
  RooRealProxy c12121 ;
  RooRealProxy c12122 ;
  RooRealProxy c12124 ;
  RooRealProxy c12126 ;
  RooRealProxy c12200 ;
  RooRealProxy c12201 ;
  RooRealProxy c12202 ;
  RooRealProxy c12204 ;
  RooRealProxy c12206 ;
  RooRealProxy c12210 ;
  RooRealProxy c12211 ;
  RooRealProxy c12212 ;
  RooRealProxy c12214 ;
  RooRealProxy c12216 ;
  RooRealProxy c12220 ;
  RooRealProxy c12221 ;
  RooRealProxy c12222 ;
  RooRealProxy c12224 ;
  RooRealProxy c20000 ;
  RooRealProxy c20001 ;
  RooRealProxy c20002 ;
  RooRealProxy c20004 ;
  RooRealProxy c20006 ;
  RooRealProxy c20010 ;
  RooRealProxy c20011 ;
  RooRealProxy c20012 ;
  RooRealProxy c20014 ;
  RooRealProxy c20016 ;
  RooRealProxy c20020 ;
  RooRealProxy c20021 ;
  RooRealProxy c20022 ;
  RooRealProxy c20024 ;
  RooRealProxy c20026 ;
  RooRealProxy c20100 ;
  RooRealProxy c20101 ;
  RooRealProxy c20102 ;
  RooRealProxy c20104 ;
  RooRealProxy c20106 ;
  RooRealProxy c20110 ;
  RooRealProxy c20111 ;
  RooRealProxy c20112 ;
  RooRealProxy c20114 ;
  RooRealProxy c20116 ;
  RooRealProxy c20120 ;
  RooRealProxy c20121 ;
  RooRealProxy c20122 ;
  RooRealProxy c20124 ;
  RooRealProxy c20126 ;
  RooRealProxy c20200 ;
  RooRealProxy c20201 ;
  RooRealProxy c20202 ;
  RooRealProxy c20204 ;
  RooRealProxy c20206 ;
  RooRealProxy c20210 ;
  RooRealProxy c20211 ;
  RooRealProxy c20212 ;
  RooRealProxy c20214 ;
  RooRealProxy c20216 ;
  RooRealProxy c20220 ;
  RooRealProxy c20221 ;
  RooRealProxy c20222 ;
  RooRealProxy c20224 ;
  RooRealProxy c20226 ;
  RooRealProxy c21000 ;
  RooRealProxy c21001 ;
  RooRealProxy c21002 ;
  RooRealProxy c21004 ;
  RooRealProxy c21006 ;
  RooRealProxy c21010 ;
  RooRealProxy c21011 ;
  RooRealProxy c21012 ;
  RooRealProxy c21014 ;
  RooRealProxy c21016 ;
  RooRealProxy c21020 ;
  RooRealProxy c21021 ;
  RooRealProxy c21022 ;
  RooRealProxy c21024 ;
  RooRealProxy c21026 ;
  RooRealProxy c21100 ;
  RooRealProxy c21101 ;
  RooRealProxy c21102 ;
  RooRealProxy c21104 ;
  RooRealProxy c21106 ;
  RooRealProxy c21110 ;
  RooRealProxy c21111 ;
  RooRealProxy c21112 ;
  RooRealProxy c21114 ;
  RooRealProxy c21116 ;
  RooRealProxy c21120 ;
  RooRealProxy c21121 ;
  RooRealProxy c21122 ;
  RooRealProxy c21124 ;
  RooRealProxy c21126 ;
  RooRealProxy c21200 ;
  RooRealProxy c21201 ;
  RooRealProxy c21202 ;
  RooRealProxy c21204 ;
  RooRealProxy c21206 ;
  RooRealProxy c21210 ;
  RooRealProxy c21211 ;
  RooRealProxy c21212 ;
  RooRealProxy c21214 ;
  RooRealProxy c21216 ;
  RooRealProxy c21220 ;
  RooRealProxy c21221 ;
  RooRealProxy c21222 ;
  RooRealProxy c21224 ;
  RooRealProxy c22000 ;
  RooRealProxy c22001 ;
  RooRealProxy c22002 ;
  RooRealProxy c22004 ;
  RooRealProxy c22006 ;
  RooRealProxy c22010 ;
  RooRealProxy c22011 ;
  RooRealProxy c22012 ;
  RooRealProxy c22014 ;
  RooRealProxy c22016 ;
  RooRealProxy c22020 ;
  RooRealProxy c22021 ;
  RooRealProxy c22022 ;
  RooRealProxy c22024 ;
  RooRealProxy c22026 ;
  RooRealProxy c22100 ;
  RooRealProxy c22101 ;
  RooRealProxy c22102 ;
  RooRealProxy c22104 ;
  RooRealProxy c22106 ;
  RooRealProxy c22110 ;
  RooRealProxy c22111 ;
  RooRealProxy c22112 ;
  RooRealProxy c22114 ;
  RooRealProxy c22116 ;
  RooRealProxy c22120 ;
  RooRealProxy c22121 ;
  RooRealProxy c22122 ;
  RooRealProxy c22124 ;
  RooRealProxy c22200 ;
  RooRealProxy c22201 ;
  RooRealProxy c22202 ;
  RooRealProxy c22204 ;
  RooRealProxy c22206 ;
  RooRealProxy c22210 ;
  RooRealProxy c22211 ;
  RooRealProxy c22212 ;
  RooRealProxy c22214 ;
  RooRealProxy c22220 ;
  RooRealProxy c22221 ;
  RooRealProxy c22222 ;
  RooRealProxy c22224 ;
  
  Double_t evaluate() const ;

static const int ordermaxi=4;
static const int ordermaxj=4;
static const int ordermaxk=4;
static const int ordermaxl=4;
static const int ordermaxm=7;

private:

  ClassDef(RooLegendre5Pdf,1) // Your description goes here...
};
 
#endif
