/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOLBTOJPSIL0WACC3PDF
#define ROOLBTOJPSIL0WACC3PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooListProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "functions.h"

class RooLbtoJpsiL0wAccPDF3 : public RooAbsPdf {
public:
  RooLbtoJpsiL0wAccPDF3() {} ; 
  RooLbtoJpsiL0wAccPDF3(const char *name, const char *title,
			RooAbsReal& _costheta0,
			RooAbsReal& _costheta1,
			RooAbsReal& _costheta2,
			RooAbsReal& P_b, RooAbsReal&  alpha_b,  RooAbsReal& alpha_lambda,  RooAbsReal& r_0,  RooAbsReal& r_1,RooArgList& _varlist);

  RooLbtoJpsiL0wAccPDF3(const RooLbtoJpsiL0wAccPDF3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooLbtoJpsiL0wAccPDF3(*this,newname); }
  inline virtual ~RooLbtoJpsiL0wAccPDF3() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy costheta0 ;
  RooRealProxy costheta1 ;
  RooRealProxy costheta2 ; 
  RooRealProxy P_b, alpha_b, alpha_lambda, r_0, r_1;  
  RooListProxy varlist;
 
  Double_t evaluate() const ;

private:

  static constexpr double pi=3.141592654;

  ClassDef(RooLbtoJpsiL0wAccPDF3,1) // Your description goes here...
};
 
#endif
