/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYPDF
#define ROOMYPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyPdf : public RooAbsPdf {
public:
  RooMyPdf() {} ; 
  RooMyPdf(const char *name, const char *title,
	      RooAbsReal& _costheta0,
	      RooAbsReal& _costheta1,
	      RooAbsReal& _costheta2,
	      RooAbsReal& _phi1,
	      RooAbsReal& _phi2,
	      RooAbsReal& _c00000,
	      RooAbsReal& _c00001,
	      RooAbsReal& _c00010,
	      RooAbsReal& _c00011,
	      RooAbsReal& _c00100,
	      RooAbsReal& _c00101,
	      RooAbsReal& _c00110,
	      RooAbsReal& _c00111,
	      RooAbsReal& _c01000,
	      RooAbsReal& _c01001,
	      RooAbsReal& _c01010,
	      RooAbsReal& _c01011,
	      RooAbsReal& _c01100,
	      RooAbsReal& _c01101,
	      RooAbsReal& _c01110,
	      RooAbsReal& _c01111,
	      RooAbsReal& _c10000,
	      RooAbsReal& _c10001,
	      RooAbsReal& _c10010,
	      RooAbsReal& _c10011,
	      RooAbsReal& _c10100,
	      RooAbsReal& _c10101,
	      RooAbsReal& _c10110,
	      RooAbsReal& _c10111,
	      RooAbsReal& _c11000,
	      RooAbsReal& _c11001,
	      RooAbsReal& _c11010,
	      RooAbsReal& _c11011,
	      RooAbsReal& _c11100,
	      RooAbsReal& _c11101,
	      RooAbsReal& _c11110,
	      RooAbsReal& _c11111);
  RooMyPdf(const RooMyPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyPdf(*this,newname); }
  inline virtual ~RooMyPdf() { }

protected:

  RooRealProxy costheta0 ;
  RooRealProxy costheta1 ;
  RooRealProxy costheta2 ;
  RooRealProxy phi1 ;
  RooRealProxy phi2 ;
  RooRealProxy c00000 ;
  RooRealProxy c00001 ;
  RooRealProxy c00010 ;
  RooRealProxy c00011 ;
  RooRealProxy c00100 ;
  RooRealProxy c00101 ;
  RooRealProxy c00110 ;
  RooRealProxy c00111 ;
  RooRealProxy c01000 ;
  RooRealProxy c01001 ;
  RooRealProxy c01010 ;
  RooRealProxy c01011 ;
  RooRealProxy c01100 ;
  RooRealProxy c01101 ;
  RooRealProxy c01110 ;
  RooRealProxy c01111 ;
  RooRealProxy c10000 ;
  RooRealProxy c10001 ;
  RooRealProxy c10010 ;
  RooRealProxy c10011 ;
  RooRealProxy c10100 ;
  RooRealProxy c10101 ;
  RooRealProxy c10110 ;
  RooRealProxy c10111 ;
  RooRealProxy c11000 ;
  RooRealProxy c11001 ;
  RooRealProxy c11010 ;
  RooRealProxy c11011 ;
  RooRealProxy c11100 ;
  RooRealProxy c11101 ;
  RooRealProxy c11110 ;
  RooRealProxy c11111 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMyPdf,1) // Your description goes here...
};
 
#endif
